
repos:
  # Ruff - Fast Python linter & formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix,]
      # Run the formatter
      - id: ruff-format

  # Bandit - Security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  # Django-specific checks
  - repo: local
    hooks:
      - id: django-check
        name: Django System Check
        entry: python manage.py check
        language: system
        pass_filenames: false
        always_run: true

  # Check for merge conflicts
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: detect-private-key

  # Check Django templates
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-django
        args: [--reformat,]
        files: \.(html|jinja)$

  # Python import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black, --line-length, "88"]


# Configuration for specific hooks
default_language_version:
  python: python3.11

# Exclude certain files/directories
exclude: |
  (?x)^(
      migrations/.*|
      .*/migrations/.*|
      staticfiles/.*|
      media/.*|
      .venv/.*|
      venv/.*|
      node_modules/.*
  )$
