---
site_name: Orange Cyber Rating documentation
repo_url: https://gitlab.tech.orange/cyber-rating/cyber-rating-portal/orange-cyberrating/
nav:
  - Home: index.md
  - Installation:
      - Prerequisites: install/prerequisites.md
      - Instructions for development install: install/install_for_dev.md
      - Instructions for server install and update: install/install_and_update.md
      - Additional information: install/additional_information.md
      - Unittests and functional tests: install/gitlab_tests.md
  - Useful commands: useful_commands.md
  - Architecture: architecture.md
  - Functional documentation:
      - Pages navigation:
          - Navbar: functional_specifications/navbar.md
          - Data display: functional_specifications/data_display.md
          - Admin panel: functional_specifications/admin_panel.md
      - Jobs: functional_specifications/jobs.md
      - Critical asset workflow: functional_specifications/critical_asset_workflow.md
      - Permission: functional_specifications/permission.md
      - API: functional_specifications/api.md
  - About: about.md
# info from https://gitlab.tech.orange/oronap/doc/doc/-/blob/master/mkdocs.yml
# good examples:
# - https://oronap.pages.gitlab.tech.orange/doc/doc/
# - https://gitlab.tech.orange/dixsiptal/documentation/newdelivery-for-partners/-/blob/master/mkdocs.yml
# Theming and options
# Configuration
theme:
  name: material
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  logo: assets/orange-logo.svg
  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    - instant
    - content.code.copy
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Helvetica Neue
    code: Helvetica
  icon:
    logo: assets/cyberating_orange_logo.png
    repo: fontawesome/brands/gitlab
  favicon: assets/cyberating_orange_logo.png
## Extra config with CSS file
extra_css:
  - stylesheets/extra.css
extra_javascript: [ ]
# Plugins
plugins:
  - search
  - awesome-pages
  - gitsnippet
  - minify:
      minify_html: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
