# Generated by Django 5.2.7 on 2025-11-06 20:41

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="إدريسي مارت",
                        max_length=200,
                        verbose_name="العنوان - Title",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="تميّزك… ملموس",
                        max_length=200,
                        verbose_name="الشعار - Tagline",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        default="منصتك للتجارة الإلكترونية المتكاملة",
                        max_length=300,
                        verbose_name="العنوان الفرعي - Subtitle",
                    ),
                ),
                (
                    "who_we_are_title",
                    models.CharField(
                        default="من نحن؟", max_length=100, verbose_name="عنوان من نحن"
                    ),
                ),
                (
                    "who_we_are_content",
                    models.TextField(verbose_name="محتوى من نحن - Who We Are Content"),
                ),
                (
                    "vision_title",
                    models.CharField(
                        default="رؤيتنا", max_length=100, verbose_name="عنوان الرؤية"
                    ),
                ),
                (
                    "vision_content",
                    models.TextField(verbose_name="محتوى الرؤية - Vision Content"),
                ),
                (
                    "mission_title",
                    models.CharField(
                        default="رسالتنا", max_length=100, verbose_name="عنوان الرسالة"
                    ),
                ),
                (
                    "mission_content",
                    models.TextField(verbose_name="محتوى الرسالة - Mission Content"),
                ),
                (
                    "values_title",
                    models.CharField(
                        default="قيمنا", max_length=100, verbose_name="عنوان القيم"
                    ),
                ),
                (
                    "vendors_count",
                    models.IntegerField(
                        default=500, verbose_name="عدد البائعين - Vendors Count"
                    ),
                ),
                (
                    "products_count",
                    models.IntegerField(
                        default=5000, verbose_name="عدد المنتجات - Products Count"
                    ),
                ),
                (
                    "customers_count",
                    models.IntegerField(
                        default=10000, verbose_name="عدد العملاء - Customers Count"
                    ),
                ),
                (
                    "categories_count",
                    models.IntegerField(
                        default=20, verbose_name="عدد الفئات - Categories Count"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Page",
                "verbose_name_plural": "About Pages",
                "db_table": "about_page",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="رقم الهاتف الرئيسي للمنصة",
                        max_length=20,
                        verbose_name="رقم الهاتف - Phone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="البريد الإلكتروني الرئيسي للمنصة",
                        max_length=254,
                        verbose_name="البريد الإلكتروني - Email",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="عنوان المكتب الرئيسي",
                        verbose_name="العنوان - Address",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        default="السبت - الخميس، 9:00 ص - 5:00 م",
                        max_length=100,
                        verbose_name="ساعات العمل - Working Hours",
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="واتساب - WhatsApp"
                    ),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, verbose_name="فيسبوك - Facebook"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, verbose_name="تويتر - Twitter"),
                ),
                (
                    "instagram",
                    models.URLField(blank=True, verbose_name="انستغرام - Instagram"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, verbose_name="لينكدإن - LinkedIn"),
                ),
                (
                    "map_embed_url",
                    models.TextField(
                        blank=True,
                        help_text="رابط الخريطة من Google Maps",
                        verbose_name="رابط الخريطة - Map Embed URL",
                    ),
                ),
                (
                    "google_maps_link",
                    models.URLField(
                        blank=True,
                        help_text="رابط مباشر إلى الموقع على Google Maps",
                        verbose_name="رابط Google Maps - Google Maps Link",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Information",
                "verbose_name_plural": "Contact Information",
                "db_table": "contact_info",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("default", "افتراضي - Default"),
                            ("service", "خدمي - Service Provider"),
                            ("merchant", "تاجر - Merchant"),
                            ("educational", "تعليمي - Educational"),
                        ],
                        default="default",
                        max_length=20,
                        verbose_name="نوع الحساب - Profile Type",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("visitor", "زائر - Visitor"),
                            ("technical", "فني - Technical"),
                            ("engineer", "مهندس - Engineer"),
                            ("company", "شركة - Company"),
                            ("lecturer", "محاضر - Lecturer"),
                            ("other", "أخرى - Other"),
                        ],
                        default="visitor",
                        max_length=20,
                        verbose_name="الرتبة - Rank",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="الهاتف - Phone"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="الجوال - Mobile"
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="واتساب - WhatsApp"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "غير موثق - Unverified"),
                            ("pending", "قيد المراجعة - Pending Review"),
                            ("verified", "موثق - Verified"),
                            ("rejected", "مرفوض - Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                        verbose_name="حالة التوثيق - Verification Status",
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="verifications/",
                        verbose_name="وثيقة التحقق - Verification Document",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ التوثيق"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="اسم الشركة - Company Name",
                    ),
                ),
                (
                    "company_name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="اسم الشركة بالعربية"
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="الرقم الضريبي - Tax Number",
                    ),
                ),
                (
                    "commercial_register",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="السجل التجاري - Commercial Register",
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="نبذة تعريفية - Bio"),
                ),
                (
                    "bio_ar",
                    models.TextField(blank=True, verbose_name="نبذة تعريفية بالعربية"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/avatars/",
                        verbose_name="صورة الملف الشخصي",
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/covers/",
                        verbose_name="صورة الغلاف - Cover Image",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الدولة - Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة - City"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, verbose_name="العنوان - Address"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="الرمز البريدي"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="التخصص - Specialization",
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="سنوات الخبرة - Years of Experience",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="الشهادات - Certifications",
                    ),
                ),
                (
                    "portfolio",
                    models.JSONField(
                        blank=True,
                        default=list,
                        verbose_name="معرض الأعمال - Portfolio",
                    ),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, verbose_name="الموقع الإلكتروني - Website"
                    ),
                ),
                ("facebook", models.URLField(blank=True, verbose_name="فيسبوك")),
                ("twitter", models.URLField(blank=True, verbose_name="تويتر")),
                ("instagram", models.URLField(blank=True, verbose_name="انستغرام")),
                ("linkedin", models.URLField(blank=True, verbose_name="لينكدإن")),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, verbose_name="عضوية مميزة - Premium Membership"
                    ),
                ),
                (
                    "subscription_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="بداية الاشتراك"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="نهاية الاشتراك"
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monthly", "شهري - Monthly"),
                            ("yearly", "سنوي - Yearly"),
                        ],
                        max_length=20,
                        verbose_name="نوع الاشتراك",
                    ),
                ),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="إجمالي المبيعات",
                    ),
                ),
                (
                    "total_purchases",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="إجمالي المشتريات",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="التقييم - Rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.IntegerField(default=0, verbose_name="عدد التقييمات"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                (
                    "is_suspended",
                    models.BooleanField(default=False, verbose_name="معلق - Suspended"),
                ),
                (
                    "suspension_reason",
                    models.TextField(blank=True, verbose_name="سبب التعليق"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="custom_user_set",
                        related_query_name="custom_user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "permissions": [
                    (
                        "can_post_classified_ads",
                        "يمكنه نشر الإعلانات المبوبة - Can post classified ads",
                    ),
                    (
                        "can_feature_classified_ads",
                        "يمكنه تمييز الإعلانات - Can feature classified ads",
                    ),
                    ("can_sell_products", "يمكنه بيع المنتجات - Can sell products"),
                    ("can_manage_store", "يمكنه إدارة المتجر - Can manage store"),
                    (
                        "can_view_sales_reports",
                        "يمكنه عرض تقارير المبيعات - Can view sales reports",
                    ),
                    ("can_offer_services", "يمكنه تقديم الخدمات - Can offer services"),
                    (
                        "can_bid_on_services",
                        "يمكنه تقديم عروض على طلبات الخدمات - Can bid on service requests",
                    ),
                    (
                        "can_request_services",
                        "يمكنه طلب الخدمات - Can request services",
                    ),
                    (
                        "can_create_courses",
                        "يمكنه إنشاء الدورات التدريبية - Can create training courses",
                    ),
                    ("can_manage_courses", "يمكنه إدارة الدورات - Can manage courses"),
                    (
                        "can_enroll_courses",
                        "يمكنه التسجيل في الدورات - Can enroll in courses",
                    ),
                    ("can_post_jobs", "يمكنه نشر الوظائف - Can post jobs"),
                    (
                        "can_apply_jobs",
                        "يمكنه التقديم على الوظائف - Can apply for jobs",
                    ),
                    (
                        "can_review_products",
                        "يمكنه تقييم المنتجات - Can review products",
                    ),
                    (
                        "can_review_services",
                        "يمكنه تقييم الخدمات - Can review services",
                    ),
                    ("can_review_courses", "يمكنه تقييم الدورات - Can review courses"),
                    ("can_review_users", "يمكنه تقييم المستخدمين - Can review users"),
                    (
                        "can_access_premium_features",
                        "يمكنه الوصول للمزايا المميزة - Can access premium features",
                    ),
                    (
                        "can_boost_listings",
                        "يمكنه تعزيز الإعلانات - Can boost listings",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم - Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="الاسم بالعربية"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(unique=True, verbose_name="الرابط الإنجليزي"),
                ),
                (
                    "slug_ar",
                    models.SlugField(
                        blank=True,
                        help_text="رابط صديق للعربية يمكن استخدامه في عناوين URL",
                        unique=True,
                        verbose_name="الرابط العربي - Arabic Slug",
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("job", "التوظيف - Jobs"),
                            ("course", "الدورات التدريبية - Training Courses"),
                            ("service", "طلب خدمة - Services"),
                            ("product", "متجر - Marketplace"),
                            ("classified", "إعلانات مبوبة - Classified Ads"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="الوصف - Description"),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                (
                    "custom_field_schema",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='A list of custom field names applicable to this category, e.g., ["brand", "condition"]',
                        verbose_name="مخطط الحقول المخصصة",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("meta_keywords", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "countries",
                    models.ManyToManyField(
                        blank=True,
                        help_text="الدول التي يتوفر فيها هذا القسم",
                        related_name="available_categories",
                        to="content.country",
                        verbose_name="الدول المتاحة - Available Countries",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        help_text="القسم متاح في هذه الدولة",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="content.country",
                        verbose_name="الدولة - Country",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["section_type", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AdPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الباقة")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الباقة"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
                ("ad_count", models.PositiveIntegerField(verbose_name="عدد الإعلانات")),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="صلاحية الباقة (بالأيام)"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="باقة افتراضية للمستخدمين الجدد"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="إذا تم تحديده، ستكون هذه الباقة مخصصة لهذا القسم فقط",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Package",
                "verbose_name_plural": "Ad Packages",
                "db_table": "ad_packages",
            },
        ),
        migrations.CreateModel(
            name="ClassifiedAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان الإعلان"),
                ),
                ("description", models.TextField(verbose_name="وصف الإعلان")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="السعر"
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False, verbose_name="السعر قابل للتفاوض"
                    ),
                ),
                (
                    "custom_fields",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="حقول مخصصة"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="العنوان"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط فيديو"),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ads/videos/",
                        verbose_name="ملف فيديو",
                    ),
                ),
                (
                    "is_cart_enabled",
                    models.BooleanField(default=False, verbose_name="تفعيل سلة الحجز"),
                ),
                (
                    "is_delivery_available",
                    models.BooleanField(default=False, verbose_name="توفير التوصيل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة - Draft"),
                            ("pending", "قيد المراجعة - Pending"),
                            ("active", "نشط - Active"),
                            ("expired", "منتهي - Expired"),
                            ("sold", "مباع - Sold"),
                            ("rejected", "مرفوض - Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classified_ads",
                        to="main.category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classified_ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classified Ad",
                "verbose_name_plural": "Classified Ads",
                "db_table": "classified_ads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ads/images/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.classifiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Image",
                "verbose_name_plural": "Ad Images",
                "db_table": "ad_images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AdFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("pinned", "تثبيت - Pinned"),
                            ("top_search", "أعلى نتائج البحث - Top Search"),
                            ("featured_section", "قسم مميز - Featured Section"),
                            ("video", "إضافة فيديو - Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="main.classifiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Feature",
                "verbose_name_plural": "Ad Features",
                "db_table": "ad_features",
            },
        ),
        migrations.CreateModel(
            name="CompanyValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="العنوان - Title"),
                ),
                ("description", models.TextField(verbose_name="الوصف - Description")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="مثال: fas fa-check",
                        max_length=100,
                        verbose_name="فئة الأيقونة - Icon Class",
                    ),
                ),
                (
                    "svg_icon",
                    models.TextField(
                        blank=True,
                        help_text="كود SVG للأيقونة",
                        verbose_name="أيقونة SVG - SVG Icon",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(default=0, verbose_name="الترتيب - Order"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "about_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="main.aboutpage",
                        verbose_name="صفحة من نحن",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Value",
                "verbose_name_plural": "Company Values",
                "db_table": "company_values",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم - Name")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="البريد الإلكتروني - Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="رقم الهاتف - Phone"
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="الموضوع - Subject"),
                ),
                ("message", models.TextField(verbose_name="الرسالة - Message")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار - Pending"),
                            ("read", "مقروءة - Read"),
                            ("replied", "تم الرد - Replied"),
                            ("resolved", "محلولة - Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة - Status",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="ملاحظات الإدارة - Admin Notes"
                    ),
                ),
                (
                    "replied_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الرد - Reply Date"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإرسال - Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم - User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "db_table": "contact_messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="الرسالة")),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                ("link", models.URLField(blank=True, null=True, verbose_name="رابط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                ("ads_remaining", models.PositiveIntegerField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.adpackage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Package",
                "verbose_name_plural": "User Packages",
                "db_table": "user_packages",
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="UserPermissionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(max_length=100, verbose_name="الإجراء - Action"),
                ),
                ("description", models.TextField(verbose_name="الوصف - Description")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permission Log",
                "verbose_name_plural": "Permission Logs",
                "db_table": "user_permission_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("monthly", "شهري - Monthly"),
                            ("yearly", "سنوي - Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="التجديد التلقائي"),
                ),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "user_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserVerificationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("national_id", "بطاقة الهوية - National ID"),
                            ("passport", "جواز السفر - Passport"),
                            (
                                "commercial_register",
                                "السجل التجاري - Commercial Register",
                            ),
                            ("tax_certificate", "شهادة ضريبية - Tax Certificate"),
                            (
                                "professional_license",
                                "رخصة مهنية - Professional License",
                            ),
                            ("other", "أخرى - Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(upload_to="verification_documents/"),
                ),
                ("additional_documents", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات - Notes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unverified", "غير موثق - Unverified"),
                            ("pending", "قيد المراجعة - Pending Review"),
                            ("verified", "موثق - Verified"),
                            ("rejected", "مرفوض - Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verification Request",
                "verbose_name_plural": "Verification Requests",
                "db_table": "user_verification_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم البحث")),
                ("query_params", models.TextField(verbose_name="معلمات البحث")),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="تفعيل إشعارات البريد الإلكتروني"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر إشعار أرسل في"
                    ),
                ),
                (
                    "unsubscribe_token",
                    models.UUIDField(db_index=True, editable=False, unique=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "db_table": "saved_searches",
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
