# Generated by Django 5.2.7 on 2025-11-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("default", "افتراضي - Default"),
                    ("service", "خدمي - Service Provider"),
                    ("merchant", "تاجر - Merchant"),
                    ("educational", "تعليمي - Educational"),
                    ("publisher", "ناشر - Publisher"),
                ],
                default="default",
                max_length=20,
                verbose_name="نوع الحساب - Profile Type",
            ),
        ),
    ]
