# Generated by Django 5.2.7 on 2025-11-06 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='features_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='سعر الميزات الإضافية'),
        ),
        migrations.CreateModel(
            name='AdReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الحجز')),
                ('full_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الكامل')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('cancelled', 'ملغي'), ('completed', 'مكتمل'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('delivery_address', models.TextField(blank=True, verbose_name='عنوان التوصيل')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='وقت انتهاء الحجز', verbose_name='ينتهي في')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.classifiedad', verbose_name='الإعلان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Ad Reservation',
                'verbose_name_plural': 'Ad Reservations',
                'db_table': 'ad_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ad_post', 'نشر إعلان'), ('feature_purchase', 'شراء ميزة'), ('package_purchase', 'شراء باقة'), ('reservation', 'حجز'), ('payment_completion', 'إكمال دفع'), ('refund', 'استرداد'), ('commission', 'عمولة المنصة')], max_length=20, verbose_name='نوع المعاملة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('cancelled', 'ملغي'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='طريقة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='رقم المعاملة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.classifiedad', verbose_name='الإعلان')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.adreservation', verbose_name='الحجز')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Ad Transaction',
                'verbose_name_plural': 'Ad Transactions',
                'db_table': 'ad_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='تفعيل سلة الحجز')),
                ('reservation_percentage', models.DecimalField(decimal_places=2, default=20.0, help_text='نسبة مبلغ الحجز من السعر الكامل', max_digits=5, verbose_name='نسبة الحجز %')),
                ('minimum_reservation', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='أقل مبلغ حجز')),
                ('maximum_reservation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='أعلى مبلغ حجز')),
                ('delivery_enabled', models.BooleanField(default=False, verbose_name='تفعيل التوصيل')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم التوصيل')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_settings', to='main.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'Cart Settings',
                'verbose_name_plural': 'Cart Settings',
                'db_table': 'cart_settings',
            },
        ),
        migrations.CreateModel(
            name='AdFeaturePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('pinned', 'تثبيت - Pinned'), ('top_search', 'أعلى نتائج البحث - Top Search'), ('featured_section', 'قسم مميز - Featured Section'), ('video', 'إضافة فيديو - Video')], max_length=20, verbose_name='نوع الميزة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('duration_days', models.PositiveIntegerField(default=7, verbose_name='مدة الميزة (بالأيام)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_prices', to='main.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'Ad Feature Price',
                'verbose_name_plural': 'Ad Feature Prices',
                'db_table': 'ad_feature_prices',
                'unique_together': {('category', 'feature_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('label_ar', models.CharField(max_length=100, verbose_name='التسمية بالعربية')),
                ('label_en', models.CharField(blank=True, max_length=100, verbose_name='التسمية بالإنجليزية')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('email', 'بريد إلكتروني'), ('url', 'رابط'), ('phone', 'هاتف'), ('select', 'خيارات متعددة'), ('checkbox', 'خانة اختيار'), ('radio', 'اختيار واحد'), ('textarea', 'نص طويل'), ('date', 'تاريخ'), ('time', 'وقت'), ('datetime', 'تاريخ ووقت'), ('color', 'لون'), ('range', 'نطاق'), ('file', 'ملف')], max_length=20, verbose_name='نوع الحقل')),
                ('is_required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('help_text', models.TextField(blank=True, verbose_name='نص المساعدة')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='نص تذكيري')),
                ('default_value', models.CharField(blank=True, max_length=500, verbose_name='القيمة الافتراضية')),
                ('options', models.TextField(blank=True, help_text='خيارات مفصولة بفاصلة (للحقول من نوع select, radio, checkbox)', verbose_name='الخيارات')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للطول')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للطول')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للقيمة')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للقيمة')),
                ('validation_regex', models.CharField(blank=True, max_length=200, verbose_name='نمط التحقق (Regex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='main.category', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'Custom Field',
                'verbose_name_plural': 'Custom Fields',
                'db_table': 'custom_fields',
                'ordering': ['category', 'order', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
