# Generated by Django 5.2.7 on 2025-10-18 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, help_text='الشركة التي تدير هذا القسم', limit_choices_to={'profile_type__in': ['merchant', 'service', 'educational']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_categories', to=settings.AUTH_USER_MODEL, verbose_name='الشركة - Company'),
        ),
        migrations.AddField(
            model_name='category',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='الدول التي يتوفر فيها هذا القسم', related_name='available_categories', to='content.country', verbose_name='الدول المتاحة - Available Countries'),
        ),
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(blank=True, help_text='القسم متاح في هذه الدولة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='content.country', verbose_name='الدولة - Country'),
        ),
    ]
