# Generated by Django 5.2.7 on 2025-10-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_category_country_company_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug_ar',
            field=models.SlugField(blank=True, help_text='رابط صديق للعربية يمكن استخدامه في عناوين URL', unique=True, verbose_name='الرابط العربي - Arabic Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='الرابط الإنجليزي'),
        ),
    ]
