# Generated by Django 5.2.7 on 2025-11-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_add_features_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifiedad",
            name="is_urgent",
            field=models.BooleanField(default=False, verbose_name="إعلان عاجل"),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="is_highlighted",
            field=models.BooleanField(default=False, verbose_name="إعلان مميز"),
        ),
    ]
