# Generated by Django 5.2.7 on 2025-11-09 00:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_auto_20251107_0020"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adpackage",
            options={
                "ordering": ["display_order", "-is_recommended", "price"],
                "verbose_name": "Ad Package",
                "verbose_name_plural": "Ad Packages",
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="link",
        ),
        migrations.AddField(
            model_name="adpackage",
            name="ad_duration_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="كم يوم سيظل كل إعلان ظاهراً",
                verbose_name="مدة ظهور الإعلان الواحد (بالأيام)",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adpackage",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="Description (English)"),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="display_order",
            field=models.PositiveIntegerField(default=0, verbose_name="ترتيب العرض"),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="feature_highlighted_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="سعر إضافي لتمييز الإعلان",
                max_digits=10,
                verbose_name="سعر التمييز",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="feature_pinned_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="سعر إضافي لتثبيت الإعلان",
                max_digits=10,
                verbose_name="سعر التثبيت",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="feature_urgent_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="سعر إضافي لجعل الإعلان عاجل",
                max_digits=10,
                verbose_name="سعر العاجل",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="قائمة بمميزات الباقة بصيغة JSON",
                verbose_name="مميزات الباقة",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="الأكثر شعبية"),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="is_recommended",
            field=models.BooleanField(
                default=False,
                help_text="عرض شارة 'موصى بها' على هذه الباقة",
                verbose_name="موصى بها",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Package Name (English)"
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="category",
            name="allow_cart",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل نظام السلة لهذا القسم",
                verbose_name="السماح بالسلة",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="default_reservation_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                help_text="النسبة المئوية الافتراضية للحجز",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="نسبة الحجز الافتراضية",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="max_reservation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="الحد الأقصى لمبلغ الحجز",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="min_reservation_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="الحد الأدنى لمبلغ الحجز",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="require_admin_approval",
            field=models.BooleanField(
                default=True,
                help_text="الإعلانات تتطلب مراجعة قبل النشر",
                verbose_name="يتطلب موافقة الإدارة",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="ملاحظات الإدارة"),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="allow_cart",
            field=models.BooleanField(
                default=False,
                help_text="تفعيل نظام السلة والحجز لهذا الإعلان",
                verbose_name="السماح بالسلة",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="cart_enabled_by_admin",
            field=models.BooleanField(
                default=False,
                help_text="يتم تفعيلها بعد استلام المنتج",
                verbose_name="السلة مفعلة من الإدارة",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="delivery_terms",
            field=models.TextField(
                blank=True,
                help_text="شروط خدمة التوصيل والتحصيل",
                verbose_name="شروط التوصيل والتحصيل",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="delivery_terms_en",
            field=models.TextField(
                blank=True, verbose_name="شروط التوصيل والتحصيل (EN)"
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="الإعلان مخفي من قبل الإدارة",
                verbose_name="مخفي",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="is_pinned",
            field=models.BooleanField(default=False, verbose_name="إعلان مثبت"),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="require_login_for_contact",
            field=models.BooleanField(
                default=False,
                help_text="إذا كان نشطاً، يجب على الزوار تسجيل الدخول لرؤية معلومات الاتصال",
                verbose_name="تسجيل الدخول مطلوب للتواصل",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="require_review",
            field=models.BooleanField(
                default=True,
                help_text="يتطلب موافقة الإدارة قبل النشر (الأعضاء الموثقين يتم نشرهم تلقائياً)",
                verbose_name="يتطلب مراجعة",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="reservation_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="المبلغ المطلوب للحجز",
                max_digits=12,
                verbose_name="مبلغ الحجز",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="reservation_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="نسبة مئوية من السعر الإجمالي للحجز",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="نسبة الحجز",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="reviewed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ المراجعة"
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_ads",
                to=settings.AUTH_USER_MODEL,
                verbose_name="تمت المراجعة بواسطة",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="visibility_type",
            field=models.CharField(
                choices=[
                    ("public", "عام - متاح للجميع"),
                    ("members_only", "للأعضاء المسجلين فقط"),
                    ("verified_only", "للأعضاء الموثقين فقط"),
                ],
                default="public",
                help_text="تحديد من يمكنه مشاهدة الإعلان",
                max_length=20,
                verbose_name="نوع الظهور",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ad_approved", "الإعلان معتمد"),
                    ("ad_rejected", "الإعلان مرفوض"),
                    ("ad_expired", "الإعلان منتهي"),
                    ("package_expired", "الباقة منتهية"),
                    ("saved_search", "نتائج البحث المحفوظ"),
                ],
                default=django.utils.timezone.now,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=200,
                verbose_name="العنوان",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="adpackage",
            name="ad_count",
            field=models.PositiveIntegerField(
                help_text="عدد الإعلانات المسموحة في هذه الباقة (غير مرتبطة بوقت)",
                verbose_name="عدد الإعلانات",
            ),
        ),
        migrations.AlterField(
            model_name="adpackage",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="إذا تم تحديده، ستكون هذه الباقة مخصصة لهذا القسم فقط",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="main.category",
                verbose_name="القسم",
            ),
        ),
        migrations.AlterField(
            model_name="adpackage",
            name="duration_days",
            field=models.PositiveIntegerField(
                help_text="صلاحية الباقة للمستخدم",
                verbose_name="صلاحية الباقة (بالأيام)",
            ),
        ),
        migrations.AlterField(
            model_name="adpackage",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="نشط"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="الرسالة"),
        ),
        migrations.AlterModelTable(
            name="notification",
            table="notifications",
        ),
    ]
