# Generated by Django 5.2.7 on 2025-10-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_arabic_slug_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
    ]
