# Generated by Django 5.2.7 on 2025-11-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_cart_wishlist_cartitem_wishlistitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("general", "عام"),
                    ("ad_approved", "الإعلان معتمد"),
                    ("ad_rejected", "الإعلان مرفوض"),
                    ("ad_expired", "الإعلان منتهي"),
                    ("package_expired", "الباقة منتهية"),
                    ("saved_search", "نتائج البحث المحفوظ"),
                ],
                max_length=20,
            ),
        ),
    ]
