# Generated by Django 5.2.7 on 2025-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mobile_verified',
            field=models.BooleanField(default=False, verbose_name='الجوال موثق - Mobile Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verification_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='رمز التحقق - Verification Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_verification_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء رمز التحقق - Code Expires'),
        ),
    ]
