# Generated by Django 5.2.7 on 2025-10-18 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_company_from_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='إدريسي مارت', max_length=200, verbose_name='العنوان - Title')),
                ('tagline', models.CharField(default='تميّزك… ملموس', max_length=200, verbose_name='الشعار - Tagline')),
                ('subtitle', models.CharField(default='منصتك للتجارة الإلكترونية المتكاملة', max_length=300, verbose_name='العنوان الفرعي - Subtitle')),
                ('who_we_are_title', models.CharField(default='من نحن؟', max_length=100, verbose_name='عنوان من نحن')),
                ('who_we_are_content', models.TextField(verbose_name='محتوى من نحن - Who We Are Content')),
                ('vision_title', models.CharField(default='رؤيتنا', max_length=100, verbose_name='عنوان الرؤية')),
                ('vision_content', models.TextField(verbose_name='محتوى الرؤية - Vision Content')),
                ('mission_title', models.CharField(default='رسالتنا', max_length=100, verbose_name='عنوان الرسالة')),
                ('mission_content', models.TextField(verbose_name='محتوى الرسالة - Mission Content')),
                ('values_title', models.CharField(default='قيمنا', max_length=100, verbose_name='عنوان القيم')),
                ('vendors_count', models.IntegerField(default=500, verbose_name='عدد البائعين - Vendors Count')),
                ('products_count', models.IntegerField(default=5000, verbose_name='عدد المنتجات - Products Count')),
                ('customers_count', models.IntegerField(default=10000, verbose_name='عدد العملاء - Customers Count')),
                ('categories_count', models.IntegerField(default=20, verbose_name='عدد الفئات - Categories Count')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط - Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'db_table': 'about_page',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='رقم الهاتف الرئيسي للمنصة', max_length=20, verbose_name='رقم الهاتف - Phone')),
                ('email', models.EmailField(help_text='البريد الإلكتروني الرئيسي للمنصة', max_length=254, verbose_name='البريد الإلكتروني - Email')),
                ('address', models.TextField(help_text='عنوان المكتب الرئيسي', verbose_name='العنوان - Address')),
                ('working_hours', models.CharField(default='السبت - الخميس، 9:00 ص - 5:00 م', max_length=100, verbose_name='ساعات العمل - Working Hours')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب - WhatsApp')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك - Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر - Twitter')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام - Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكدإن - LinkedIn')),
                ('map_embed_url', models.TextField(blank=True, help_text='رابط الخريطة من Google Maps', verbose_name='رابط الخريطة - Map Embed URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط - Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان - Title')),
                ('description', models.TextField(verbose_name='الوصف - Description')),
                ('icon_class', models.CharField(blank=True, help_text='مثال: fas fa-check', max_length=100, verbose_name='فئة الأيقونة - Icon Class')),
                ('svg_icon', models.TextField(blank=True, help_text='كود SVG للأيقونة', verbose_name='أيقونة SVG - SVG Icon')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب - Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط - Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.aboutpage', verbose_name='صفحة من نحن')),
            ],
            options={
                'verbose_name': 'Company Value',
                'verbose_name_plural': 'Company Values',
                'db_table': 'company_values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم - Name')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني - Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف - Phone')),
                ('subject', models.CharField(max_length=200, verbose_name='الموضوع - Subject')),
                ('message', models.TextField(verbose_name='الرسالة - Message')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار - Pending'), ('read', 'مقروءة - Read'), ('replied', 'تم الرد - Replied'), ('resolved', 'محلولة - Resolved')], default='pending', max_length=20, verbose_name='الحالة - Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة - Admin Notes')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد - Reply Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال - Created At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم - User')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
