# Generated by Django 5.2.7 on 2025-10-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutpage_contactinfo_companyvalue_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='google_maps_link',
            field=models.URLField(blank=True, help_text='رابط مباشر إلى الموقع على Google Maps', verbose_name='رابط Google Maps - Google Maps Link'),
        ),
    ]
