# Generated by Django 5.2.7 on 2025-11-13 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_mobile_verification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paypal', 'PayPal'), ('paymob', 'Paymob'), ('bank_transfer', 'تحويل بنكي - Bank Transfer')], max_length=20, verbose_name='مزود الدفع - Payment Provider')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=255, verbose_name='معرف المعاملة - Transaction ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ - Amount')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة - Currency')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار - Pending'), ('completed', 'مكتمل - Completed'), ('failed', 'فاشل - Failed'), ('cancelled', 'ملغي - Cancelled'), ('refunded', 'مسترد - Refunded')], default='pending', max_length=20, verbose_name='حالة الدفع - Payment Status')),
                ('description', models.TextField(blank=True, verbose_name='الوصف - Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية - Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال - Completion Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userpackage',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='main.payment', verbose_name='الدفعة - Payment'),
        ),
    ]
