# Generated by Django 5.2.7 on 2025-10-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("main", "0006_contactinfo_google_maps_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الباقة")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="وصف الباقة"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="السعر"
                    ),
                ),
                ("ad_count", models.PositiveIntegerField(verbose_name="عدد الإعلانات")),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="صلاحية الباقة (بالأيام)"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="باقة افتراضية للمستخدمين الجدد"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="إذا تم تحديده، ستكون هذه الباقة مخصصة لهذا القسم فقط",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="main.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Package",
                "verbose_name_plural": "Ad Packages",
                "db_table": "ad_packages",
            },
        ),
        migrations.CreateModel(
            name="ClassifiedAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="عنوان الإعلان"),
                ),
                ("description", models.TextField(verbose_name="وصف الإعلان")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="السعر"
                    ),
                ),
                (
                    "is_negotiable",
                    models.BooleanField(
                        default=False, verbose_name="السعر قابل للتفاوض"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="المدينة")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="العنوان"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط فيديو"),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ads/videos/",
                        verbose_name="ملف فيديو",
                    ),
                ),
                (
                    "is_cart_enabled",
                    models.BooleanField(default=False, verbose_name="تفعيل سلة الحجز"),
                ),
                (
                    "is_delivery_available",
                    models.BooleanField(default=False, verbose_name="توفير التوصيل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة - Draft"),
                            ("pending", "قيد المراجعة - Pending"),
                            ("active", "نشط - Active"),
                            ("expired", "منتهي - Expired"),
                            ("sold", "مباع - Sold"),
                            ("rejected", "مرفوض - Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ الانتهاء"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classified_ads",
                        to="main.category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="content.country",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classified_ads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Classified Ad",
                "verbose_name_plural": "Classified Ads",
                "db_table": "classified_ads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="ads/images/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.classifiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Image",
                "verbose_name_plural": "Ad Images",
                "db_table": "ad_images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AdFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("pinned", "تثبيت - Pinned"),
                            ("top_search", "أعلى نتائج البحث - Top Search"),
                            ("featured_section", "قسم مميز - Featured Section"),
                            ("video", "إضافة فيديو - Video"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="main.classifiedad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Feature",
                "verbose_name_plural": "Ad Features",
                "db_table": "ad_features",
            },
        ),
        migrations.CreateModel(
            name="UserPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateTimeField()),
                ("ads_remaining", models.PositiveIntegerField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.adpackage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Package",
                "verbose_name_plural": "User Packages",
                "db_table": "user_packages",
                "ordering": ["-purchase_date"],
            },
        ),
    ]
