# Generated by Django 5.2.7 on 2025-11-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_payment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='السؤال أو الكلمات المفتاحية', verbose_name='السؤال')),
                ('answer', models.TextField(help_text='الإجابة التفصيلية', verbose_name='الإجابة')),
                ('category', models.CharField(choices=[('general', 'عام'), ('about', 'حول الموقع'), ('services', 'الخدمات'), ('ads', 'الإعلانات'), ('marketplace', 'المتجر'), ('courses', 'الدورات'), ('jobs', 'الوظائف'), ('account', 'الحساب'), ('payment', 'الدفع'), ('support', 'الدعم الفني')], default='general', max_length=20, verbose_name='الفئة')),
                ('keywords', models.TextField(blank=True, help_text='كلمات مفتاحية مفصولة بفواصل للبحث', verbose_name='الكلمات المفتاحية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=1, help_text='أولوية عرض الإجابة (الأعلى أولاً)', verbose_name='الأولوية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قاعدة معرفة الشات بوت',
                'verbose_name_plural': 'قاعدة معرفة الشات بوت',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotQuickAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('action_type', models.CharField(choices=[('message', 'رسالة'), ('url', 'رابط'), ('search', 'بحث')], default='message', max_length=50, verbose_name='نوع الإجراء')),
                ('action_value', models.TextField(help_text='النص أو الرابط أو استعلام البحث', verbose_name='قيمة الإجراء')),
                ('icon', models.CharField(default='fas fa-question', help_text='فئة CSS للأيقونة', max_length=50, verbose_name='الأيقونة')),
                ('order', models.IntegerField(default=1, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'إجراء سريع للشات بوت',
                'verbose_name_plural': 'إجراءات سريعة للشات بوت',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, verbose_name='معرف الجلسة')),
                ('user_message', models.TextField(verbose_name='رسالة المستخدم')),
                ('bot_response', models.TextField(verbose_name='رد الشات بوت')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='مفيد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('matched_knowledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.chatbotknowledgebase', verbose_name='المعرفة المطابقة')),
            ],
            options={
                'verbose_name': 'محادثة الشات بوت',
                'verbose_name_plural': 'محادثات الشات بوت',
                'ordering': ['-created_at'],
            },
        ),
    ]
