# Generated by Django 5.2.7 on 2025-10-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_adpackage_classifiedad_adimage_adfeature_userpackage"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifiedad",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict, verbose_name="حقول مخصصة"),
        ),
    ]
