# Generated by Django 5.2.7 on 2025-11-21 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chatbotknowledgebase_chatbotquickaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpackage',
            name='package',
            field=models.ForeignKey(blank=True, help_text='الباقة المرتبطة - يمكن أن تكون فارغة للإعلانات المجانية', null=True, on_delete=django.db.models.deletion.PROTECT, to='main.adpackage'),
        ),
    ]
