# Generated by Django 5.2.7 on 2025-11-23 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_make_package_nullable_for_free_ads"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("publisher_client", "Publisher-Client"),
                            ("publisher_admin", "Publisher-Admin"),
                        ],
                        default="publisher_client",
                        max_length=20,
                        verbose_name="نوع المحادثة",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخر تحديث"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_rooms",
                        to="main.classifiedad",
                        verbose_name="الإعلان",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="العميل",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publisher_chat_rooms",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="الناشر",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "db_table": "chat_rooms",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="الرسالة")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="وقت الإرسال"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروءة")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="وقت القراءة"
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="chat_attachments/%Y/%m/",
                        verbose_name="مرفق",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المرسل",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="main.chatroom",
                        verbose_name="غرفة المحادثة",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["publisher", "client"], name="chat_rooms_publish_a6b398_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatroom",
            index=models.Index(
                fields=["room_type", "is_active"], name="chat_rooms_room_ty_a475b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="chat_messag_room_id_cc7f0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "is_read"], name="chat_messag_sender__9127fe_idx"
            ),
        ),
    ]
