# Generated by Django 5.2.7 on 2025-10-24 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_classifiedad_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="custom_field_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='A list of custom field names applicable to this category, e.g., ["brand", "condition"]',
                verbose_name="مخطط الحقول المخصصة",
            ),
        ),
        migrations.CreateModel(
            name="SavedSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم البحث")),
                ("query_params", models.TextField(verbose_name="معلمات البحث")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_searches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Search",
                "verbose_name_plural": "Saved Searches",
                "db_table": "saved_searches",
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
    ]
