# Generated by Django 5.2.7 on 2025-11-25 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_chatroom_chatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('session_key', models.CharField(db_index=True, max_length=40, verbose_name='مفتاح الجلسة')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('page_url', models.CharField(blank=True, max_length=500, verbose_name='رابط الصفحة')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='المصدر')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='الدولة')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('device_type', models.CharField(choices=[('mobile', 'موبايل'), ('tablet', 'تابلت'), ('desktop', 'كمبيوتر')], default='desktop', max_length=20, verbose_name='نوع الجهاز')),
                ('first_visit', models.DateTimeField(auto_now_add=True, verbose_name='أول زيارة')),
                ('last_activity', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر نشاط')),
                ('page_views', models.PositiveIntegerField(default=1, verbose_name='عدد الصفحات')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'db_table': 'visitors',
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['ip_address', 'session_key'], name='visitors_ip_addr_86cf3b_idx'), models.Index(fields=['last_activity'], name='visitors_last_ac_19d075_idx'), models.Index(fields=['first_visit'], name='visitors_first_v_264829_idx')],
                'unique_together': {('ip_address', 'session_key')},
            },
        ),
    ]
