# Generated by Django 5.2.7 on 2025-11-26 19:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_add_visitor_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوى الرسالة - Mission Content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوى الرؤية - Vision Content'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='who_we_are_content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='محتوى من نحن - Who We Are Content'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='الوصف - Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='admin_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='ملاحظات الإدارة'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='delivery_terms',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='شروط خدمة التوصيل والتحصيل', verbose_name='شروط التوصيل والتحصيل'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='delivery_terms_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='شروط التوصيل والتحصيل (EN)'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='وصف الإعلان'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='الوصف - Description'),
        ),
    ]
