# Generated by Django 5.2.7 on 2025-11-30 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyvalue',
            name='about_page',
        ),
        migrations.DeleteModel(
            name='AboutPage',
        ),
        migrations.DeleteModel(
            name='CompanyValue',
        ),
    ]
