# Generated by Django 5.2.7 on 2025-11-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_aboutpage_companyvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
