# Generated by Django 5.2.7 on 2025-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء رمز التحقق - Token Expires'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='رمز التحقق من البريد - Email Verification Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='البريد الإلكتروني موثق - Email Verified'),
        ),
    ]
