# Generated by Django 5.2.7 on 2025-12-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_email_verification_expires_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['name'], 'verbose_name': 'حقل مخصص', 'verbose_name_plural': 'الحقول المخصصة'},
        ),
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='مطلوب افتراضياً'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الحقل'),
        ),
        migrations.CreateModel(
            name='CategoryCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='تجاوز الإعداد الافتراضي للحقل', verbose_name='مطلوب في هذا القسم')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط في هذا القسم')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='القسم')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customfield', verbose_name='الحقل المخصص')),
            ],
            options={
                'verbose_name': 'حقل مخصص للقسم',
                'verbose_name_plural': 'الحقول المخصصة للأقسام',
                'db_table': 'category_custom_fields',
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'custom_field')},
            },
        ),
        migrations.AddField(
            model_name='customfield',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='custom_fields', through='main.CategoryCustomField', to='main.category', verbose_name='الأقسام'),
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='category',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='options',
        ),
        migrations.RemoveField(
            model_name='customfield',
            name='order',
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ar', models.CharField(max_length=200, verbose_name='الخيار بالعربية')),
                ('label_en', models.CharField(blank=True, max_length=200, verbose_name='الخيار بالإنجليزية')),
                ('value', models.CharField(max_length=200, verbose_name='القيمة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='main.customfield', verbose_name='الحقل المخصص')),
            ],
            options={
                'verbose_name': 'خيار الحقل المخصص',
                'verbose_name_plural': 'خيارات الحقول المخصصة',
                'db_table': 'custom_field_options',
                'ordering': ['custom_field', 'order', 'label_ar'],
                'unique_together': {('custom_field', 'value')},
            },
        ),
    ]
