# Generated by Django 5.2.7 on 2025-12-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_redesign_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycustomfield',
            name='show_on_card',
            field=models.BooleanField(default=False, help_text='إظهار قيمة هذا الحقل على بطاقة الإعلان من الخارج', verbose_name='إظهار على بطاقة الإعلان'),
        ),
    ]
