# Generated by Django 5.2.7 on 2025-12-07 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_show_on_card_to_category_custom_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('default', 'قياسي - Standard'), ('publisher', 'ناشر - Publisher')], default='default', max_length=20, verbose_name='نوع الحساب - Profile Type'),
        ),
        migrations.CreateModel(
            name='AdUpgradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upgrade_type', models.CharField(choices=[('highlighted', 'مميز - Highlighted'), ('urgent', 'عاجل - Urgent'), ('pinned', 'مثبت - Pinned')], max_length=20, verbose_name='نوع الترقية')),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('duration_days', models.IntegerField(verbose_name='المدة بالأيام')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_history', to='main.classifiedad')),
            ],
            options={
                'verbose_name': 'Ad Upgrade History',
                'verbose_name_plural': 'Ad Upgrade Histories',
                'db_table': 'ad_upgrade_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
