# Generated by Django 5.2.7 on 2025-12-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_add_ad_upgrade_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpackage',
            name='ads_used',
            field=models.PositiveIntegerField(default=0, help_text='عدد الإعلانات التي تم استخدامها من هذه الباقة', verbose_name='الإعلانات المستخدمة'),
        ),
    ]
