# Generated by Django 5.2.7 on 2025-12-07 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_add_ads_used_to_user_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('ad_content', 'محتوى إعلان غير لائق'), ('fraud', 'احتيال أو نصب'), ('spam', 'إعلان متكرر أو سبام'), ('wrong_category', 'قسم خاطئ'), ('user_behavior', 'سلوك مستخدم غير لائق'), ('fake_info', 'معلومات مضللة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع البلاغ')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('reviewing', 'تحت المراجعة'), ('resolved', 'تم الحل'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(help_text='يرجى تقديم تفاصيل حول البلاغ', verbose_name='وصف البلاغ')),
                ('evidence_url', models.URLField(blank=True, help_text='رابط لصورة أو دليل إضافي', null=True, verbose_name='رابط دليل')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('reported_ad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.classifiedad', verbose_name='الإعلان المبلغ عنه')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المبلغ عنه')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
            ],
            options={
                'verbose_name': 'بلاغ',
                'verbose_name_plural': 'البلاغات',
                'db_table': 'ad_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ad_reports_created_75b25e_idx'), models.Index(fields=['status'], name='ad_reports_status_eb33b2_idx'), models.Index(fields=['report_type'], name='ad_reports_report__1a97d6_idx')],
            },
        ),
    ]
