# Generated by Django 5.2.7 on 2025-12-07 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_adreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='hide_price',
            field=models.BooleanField(default=False, help_text="إخفاء السعر وإظهار زر 'الحصول على عرض سعر'", verbose_name='إخفاء السعر'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='price_on_request',
            field=models.BooleanField(default=False, help_text="إظهار 'السعر عند الطلب' بدلاً من السعر الفعلي", verbose_name='السعر عند الطلب'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='تقييم الإعلان من 0 إلى 5', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='عدد المستخدمين الذين قيموا هذا الإعلان', verbose_name='عدد التقييمات'),
        ),
    ]
