# Generated by Django 5.2.7 on 2025-12-07 01:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_add_price_options_and_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='تقييم من 1 إلى 5 نجوم', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, help_text='تعليق اختياري', verbose_name='التعليق')),
                ('is_approved', models.BooleanField(default=True, help_text='يمكن للإدارة إخفاء التعليقات غير اللائقة', verbose_name='معتمد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.classifiedad', verbose_name='الإعلان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تقييم إعلان',
                'verbose_name_plural': 'تقييمات الإعلانات',
                'db_table': 'ad_reviews',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='ad_reviews_created_070236_idx'), models.Index(fields=['ad', 'is_approved'], name='ad_reviews_ad_id_69d96c_idx')],
                'unique_together': {('ad', 'user')},
            },
        ),
    ]
