# Generated by Django 5.2.7 on 2025-12-07 02:05

from django.db import migrations, models
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    """Generate slugs for existing classified ads"""
    ClassifiedAd = apps.get_model('main', 'ClassifiedAd')

    for ad in ClassifiedAd.objects.all():
        if not ad.slug:
            # Generate base slug from title
            base_slug = slugify(ad.title, allow_unicode=True)
            slug = base_slug
            counter = 1

            # Ensure slug is unique
            while ClassifiedAd.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1

            ad.slug = slug
            ad.save(update_fields=['slug'])


def reverse_slugs(apps, schema_editor):
    """Reverse operation - clear slugs"""
    ClassifiedAd = apps.get_model('main', 'ClassifiedAd')
    ClassifiedAd.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_add_ad_review_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='slug',
            field=models.SlugField(blank=True, help_text='يتم إنشاؤه تلقائياً من عنوان الإعلان', max_length=300, verbose_name='الرابط الصديق لمحركات البحث'),
        ),
        migrations.RunPython(generate_slugs, reverse_slugs),
        # Make slug unique after populating
        migrations.AlterField(
            model_name='classifiedad',
            name='slug',
            field=models.SlugField(blank=True, help_text='يتم إنشاؤه تلقائياً من عنوان الإعلان', max_length=300, unique=True, verbose_name='الرابط الصديق لمحركات البحث'),
        ),
    ]
