# Generated by Django 5.2.7 on 2025-12-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_add_slug_to_classifiedad"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="الرابط"
            ),
        ),
    ]
