# Generated by Django 5.2.7 on 2025-12-07 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفئة - Category Name')),
                ('name_ar', models.CharField(blank=True, max_length=200, verbose_name='اسم الفئة بالعربية')),
                ('icon', models.CharField(default='fas fa-question-circle', help_text='Font Awesome icon class (e.g., fas fa-question-circle)', max_length=50, verbose_name='أيقونة - Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب - Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط - Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ Category',
                'verbose_name_plural': 'FAQ Categories',
                'db_table': 'faq_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='adtransaction',
            name='reservation',
        ),
        migrations.AddField(
            model_name='adtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم التوصيل'),
        ),
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ انتهاء الطلب (للطلبات المحجوزة)', null=True, verbose_name='ينتهي في'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المدفوع'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'غير مدفوع'), ('partial', 'دفع جزئي'), ('paid', 'مدفوع بالكامل'), ('refunded', 'مسترد')], default='unpaid', max_length=20, verbose_name='حالة الدفع'),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المتبقي'),
        ),
        migrations.AlterField(
            model_name='adtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('ad_post', 'نشر إعلان'), ('feature_purchase', 'شراء ميزة'), ('package_purchase', 'شراء باقة'), ('order_payment', 'دفع طلب'), ('payment_completion', 'إكمال دفع'), ('refund', 'استرداد'), ('commission', 'عمولة المنصة')], max_length=20, verbose_name='نوع المعاملة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('online', 'الدفع الإلكتروني'), ('partial', 'دفع جزئي')], default='cod', max_length=20, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي'), ('refunded', 'مسترد')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='السؤال - Question')),
                ('question_ar', models.CharField(blank=True, max_length=500, verbose_name='السؤال بالعربية')),
                ('answer', models.TextField(verbose_name='الإجابة - Answer')),
                ('answer_ar', models.TextField(blank=True, verbose_name='الإجابة بالعربية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب - Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط - Active')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات - Views Count')),
                ('is_popular', models.BooleanField(default=False, verbose_name='سؤال شائع - Popular Question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='main.faqcategory', verbose_name='الفئة - Category')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['category__order', 'order', '-is_popular'],
            },
        ),
        migrations.DeleteModel(
            name='AdReservation',
        ),
    ]
