# Generated by Django 5.2.7 on 2025-12-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_enhance_orders_remove_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, help_text='السماح للعملاء بدفع جزء من المبلغ عند الطلب', verbose_name='السماح بالدفع الجزئي'),
        ),
    ]
