# Generated by Django 5.2.7 on 2025-12-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_allow_partial_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
