# Generated by Django 5.2.7 on 2025-12-12 21:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_remove_quantity_from_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='الإجابة - Answer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='الإجابة بالعربية'),
        ),
    ]
