# Generated by Django 5.2.7 on 2025-12-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_faq_ckeditor5_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('online', 'الدفع الإلكتروني'), ('instapay', 'InstaPay'), ('partial', 'دفع جزئي')], default='cod', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
