# Generated by Django 5.2.7 on 2025-12-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_add_instapay_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='تلقي إشعارات حول الإعلانات والرسائل عبر البريد الإلكتروني', verbose_name='إشعارات البريد الإلكتروني'),
        ),
    ]
