# Generated by Django 5.2.7 on 2025-12-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_faq_answer_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='is_resubmitted',
            field=models.BooleanField(default=False, help_text='الإعلان تم تعديله ويحتاج مراجعة مجدداً', verbose_name='معاد إرساله'),
        ),
    ]
