# Generated by Django 5.2.7 on 2025-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_add_is_resubmitted_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_photo',
            field=models.ImageField(blank=True, help_text='صورة إيصال الدفع عبر InstaPay أو المحفظة الإلكترونية', null=True, upload_to='orders/transaction_photos/', verbose_name='صورة إيصال التحويل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'الدفع عند الاستلام'), ('online', 'الدفع الإلكتروني'), ('instapay', 'InstaPay'), ('wallet', 'محفظة إلكترونية'), ('partial', 'دفع جزئي')], default='cod', max_length=20, verbose_name='طريقة الدفع'),
        ),
    ]
