# Generated by Django 5.2.7 on 2025-12-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_add_transaction_photo_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='offline_payment_receipt',
            field=models.ImageField(blank=True, help_text='صورة الإيصال أو لقطة شاشة للتحويل', null=True, upload_to='payment_receipts/', verbose_name='إيصال الدفع اليدوي'),
        ),
    ]
