# Generated by Django 5.2.7 on 2025-12-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_add_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='adpackage',
            name='feature_contact_for_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="سعر إضافي لإخفاء السعر وعرض زر 'تواصل ليصلك عرض سعر'", max_digits=10, verbose_name="سعر ميزة 'تواصل ليصلك عرض سعر'"),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='contact_for_price',
            field=models.BooleanField(default=False, help_text="إظهار 'تواصل ليصلك عرض سعر' بدلاً من السعر (ميزة مدفوعة)", verbose_name='تواصل ليصلك عرض سعر'),
        ),
        migrations.AlterField(
            model_name='adfeature',
            name='feature_type',
            field=models.CharField(choices=[('pinned', 'تثبيت - Pinned'), ('top_search', 'أعلى نتائج البحث - Top Search'), ('featured_section', 'قسم مميز - Featured Section'), ('video', 'إضافة فيديو - Video'), ('contact_for_price', 'تواصل ليصلك عرض سعر - Contact for Price')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adfeatureprice',
            name='feature_type',
            field=models.CharField(choices=[('pinned', 'تثبيت - Pinned'), ('top_search', 'أعلى نتائج البحث - Top Search'), ('featured_section', 'قسم مميز - Featured Section'), ('video', 'إضافة فيديو - Video'), ('contact_for_price', 'تواصل ليصلك عرض سعر - Contact for Price')], max_length=20, verbose_name='نوع الميزة'),
        ),
    ]
