# Generated by Django 5.2.7 on 2025-12-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_adpackage_feature_contact_for_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycustomfield',
            name='show_in_filters',
            field=models.BooleanField(default=False, help_text='إظهار هذا الحقل كفلتر في صفحات الأقسام', verbose_name='إظهار في الفلاتر'),
        ),
    ]
