# Generated by Django 5.2.7 on 2025-12-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_add_show_in_filters_to_category_custom_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cart_instructions',
            field=models.TextField(blank=True, default='عند تفعيل السلة، يجب أن يكون السعر شاملاً رسوم الخدمة والتوصيل. سيتم خصم رسوم الخدمة منك عند البيع عبر المنصة.', help_text='نص إرشادي يظهر للناشر عند تفعيل السلة', verbose_name='إرشادات السلة'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='facebook_post_url',
            field=models.URLField(blank=True, help_text='الرابط المباشر للمنشور على فيسبوك', null=True, verbose_name='رابط المنشور على فيسبوك'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='facebook_share_completed',
            field=models.BooleanField(default=False, help_text='تم نشر الإعلان على صفحة فيسبوك', verbose_name='تم النشر على فيسبوك'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='facebook_share_requested',
            field=models.BooleanField(default=False, help_text='تم تقديم طلب للنشر على فيسبوك', verbose_name='تم طلب النشر على فيسبوك'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='facebook_shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر على فيسبوك'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='publisher_cart_enabled',
            field=models.BooleanField(default=False, help_text='الناشر طلب تفعيل السلة لهذا الإعلان', verbose_name='الناشر فعّل السلة'),
        ),
        migrations.AddField(
            model_name='classifiedad',
            name='share_on_facebook',
            field=models.BooleanField(default=False, help_text='نشر الإعلان على صفحة فيسبوك (ميزة مدفوعة)', verbose_name='نشر على فيسبوك - Share on Facebook'),
        ),
        migrations.AlterField(
            model_name='adfeature',
            name='feature_type',
            field=models.CharField(choices=[('pinned', 'تثبيت - Pinned'), ('top_search', 'أعلى نتائج البحث - Top Search'), ('featured_section', 'قسم مميز - Featured Section'), ('video', 'إضافة فيديو - Video (قيد التطوير)'), ('contact_for_price', 'تواصل ليصلك عرض سعر - Contact for Price'), ('facebook_share', 'نشر على فيسبوك - Facebook Share')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adfeatureprice',
            name='feature_type',
            field=models.CharField(choices=[('pinned', 'تثبيت - Pinned'), ('top_search', 'أعلى نتائج البحث - Top Search'), ('featured_section', 'قسم مميز - Featured Section'), ('video', 'إضافة فيديو - Video (قيد التطوير)'), ('contact_for_price', 'تواصل ليصلك عرض سعر - Contact for Price'), ('facebook_share', 'نشر على فيسبوك - Facebook Share')], max_length=20, verbose_name='نوع الميزة'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='video_file',
            field=models.FileField(blank=True, help_text='رفع ملف فيديو مباشرة (ميزة قيد التطوير)', null=True, upload_to='ad_videos/', verbose_name='ملف الفيديو - Video File'),
        ),
        migrations.AlterField(
            model_name='classifiedad',
            name='video_url',
            field=models.URLField(blank=True, help_text='رابط فيديو YouTube أو Vimeo (ميزة قيد التطوير)', null=True, verbose_name='رابط الفيديو - Video URL'),
        ),
    ]
