# Generated by Django 5.2.7 on 2025-12-30 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_category_cart_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار - Pending'), ('in_progress', 'جاري التنفيذ - In Progress'), ('completed', 'تم التنفيذ - Completed'), ('rejected', 'مرفوض - Rejected')], default='pending', max_length=20, verbose_name='الحالة')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التنفيذ')),
                ('facebook_post_url', models.URLField(blank=True, null=True, verbose_name='رابط المنشور على فيسبوك')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('payment_confirmed', models.BooleanField(default=False, verbose_name='تم تأكيد الدفع')),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ الدفع')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_share_requests', to='main.classifiedad', verbose_name='الإعلان')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_facebook_requests', to=settings.AUTH_USER_MODEL, verbose_name='تم التنفيذ بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_share_requests', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طلب نشر على فيسبوك',
                'verbose_name_plural': 'طلبات النشر على فيسبوك',
                'db_table': 'facebook_share_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', '-requested_at'], name='facebook_sh_status_1367c0_idx'), models.Index(fields=['ad', 'status'], name='facebook_sh_ad_id_d1862e_idx')],
            },
        ),
    ]
