# Generated by Django 5.2.7 on 2025-12-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_facebooksharerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='تاريخ الحذف المؤقت - يتم الحذف النهائي بعد المدة المحددة', null=True, verbose_name='تاريخ الحذف'),
        ),
    ]
