# Generated by Django 5.2.7 on 2025-12-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_add_deleted_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adreview',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='يتطلب موافقة الإدارة قبل الظهور', verbose_name='معتمد'),
        ),
    ]
