# Generated by Django 5.2.7 on 2026-01-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0042_add_country_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="SAR",
                help_text="العملة المستخدمة للطلب",
                max_length=3,
                verbose_name="العملة - Currency",
            ),
        ),
    ]
