# Generated by Django 5.2.7 on 2026-01-08 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0026_alter_paymentmethodconfig_cod_requires_deposit"),
        ("main", "0043_add_currency_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="يجب اختيار المدينة من القائمة المتاحة للدولة",
                max_length=100,
                verbose_name="المدينة - City",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="الدولة التي اختارها المستخدم عند التسجيل",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="content.country",
                verbose_name="الدولة - Country",
            ),
        ),
    ]
