# Generated by Django 5.2.7 on 2026-01-09 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_paymentmethodconfig_cod_requires_deposit'),
        ('main', '0045_user_country_foreignkey_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ban_reason',
            field=models.TextField(blank=True, verbose_name='سبب الحظر'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='حظر نهائي للمستخدم - لا يمكن تسجيل الدخول', verbose_name='محظور - Banned'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text='الدولة التي اختارها المستخدم عند التسجيل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='content.country', verbose_name='الدولة - Country'),
        ),
    ]
