# Generated by Django 5.2.7 on 2026-01-12 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0046_add_user_ban_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ad_creation_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="السعر المطلوب لإنشاء إعلان في هذا القسم (إذا لم يكن لدى المستخدم إعلانات مجانية)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="سعر إنشاء الإعلان",
            ),
        ),
    ]
