# Generated by Django 5.2.7 on 2026-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_category_ad_creation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedad',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='تم دفع رسوم نشر الإعلان', verbose_name='مدفوع'),
        ),
    ]
