# Generated by Django 5.2.7 on 2026-02-28 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_order_add_paypal_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='suggested_ad_price',
        ),
    ]
