# Generated by Django 5.2.7 on 2026-03-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0050_remove_suggested_ad_price_from_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyTip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان النصيحة (مثال: قابل البائع شخصياً)",
                        max_length=200,
                        verbose_name="العنوان - Title",
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        help_text="English title for the tip",
                        max_length=200,
                        verbose_name="Title (English)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="وصف تفصيلي للنصيحة",
                        verbose_name="الوصف - Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        blank=True,
                        help_text="English description for the tip",
                        verbose_name="Description (English)",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-info-circle",
                        help_text="FontAwesome icon class (e.g., fas fa-handshake)",
                        max_length=100,
                        verbose_name="أيقونة - Icon Class",
                    ),
                ),
                (
                    "color_theme",
                    models.CharField(
                        choices=[
                            ("tip-blue", "أزرق - Blue"),
                            ("tip-green", "أخضر - Green"),
                            ("tip-orange", "برتقالي - Orange"),
                            ("tip-red", "أحمر - Red"),
                            ("tip-purple", "بنفسجي - Purple"),
                            ("tip-teal", "تركواز - Teal"),
                        ],
                        default="tip-blue",
                        max_length=20,
                        verbose_name="نمط اللون - Color Theme",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="إظهار هذه النصيحة للمستخدمين",
                        verbose_name="نشط - Active",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب عرض النصيحة (الأقل رقماً يظهر أولاً)",
                        verbose_name="الترتيب - Order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اختر عدة فئات لعرض هذه النصيحة فيها",
                        related_name="multi_safety_tips",
                        to="main.category",
                        verbose_name="فئات متعددة - Multiple Categories",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="اختر فئة محددة أو اتركها فارغة للتطبيق على جميع الفئات",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_tips",
                        to="main.category",
                        verbose_name="الفئة - Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "نصيحة أمان",
                "verbose_name_plural": "نصائح الأمان",
                "db_table": "safety_tips",
                "ordering": ["order", "id"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "order"],
                        name="safety_tips_is_acti_f72fa8_idx",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="safety_tips_categor_c86ab3_idx",
                    ),
                ],
            },
        ),
    ]
