# Generated by Django 5.2.7 on 2026-01-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0999_add_verified_user_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="userverificationrequest",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاريخ الدفع - Paid At"
            ),
        ),
        migrations.AddField(
            model_name="userverificationrequest",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="مبلغ الدفع - Payment Amount",
            ),
        ),
        migrations.AddField(
            model_name="userverificationrequest",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="طريقة الدفع - Payment Method"
            ),
        ),
        migrations.AddField(
            model_name="userverificationrequest",
            name="payment_required",
            field=models.BooleanField(
                default=False,
                help_text="Whether this verification requires payment",
                verbose_name="يتطلب دفع - Payment Required",
            ),
        ),
        migrations.AddField(
            model_name="userverificationrequest",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "قيد الانتظار - Pending"),
                    ("paid", "مدفوع - Paid"),
                    ("failed", "فشل - Failed"),
                    ("refunded", "مسترد - Refunded"),
                ],
                default="pending",
                max_length=20,
                verbose_name="حالة الدفع - Payment Status",
            ),
        ),
        migrations.AddField(
            model_name="userverificationrequest",
            name="payment_transaction_id",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="رقم المعاملة - Transaction ID"
            ),
        ),
    ]
