# Generated by Django 5.2.7 on 2026-02-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_suggested_ad_price"),
        ("main", "1000_add_verification_payment_fields"),
    ]

    operations = []
