# Generated by Django 5.2.7 on 2026-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1001_merge_20260223_2027"),
    ]

    operations = [
        migrations.AddField(
            model_name="adpackage",
            name="feature_add_video_price",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                help_text="سعر إضافي لإرفاق فيديو بالإعلان",
                max_digits=10,
                verbose_name="سعر إضافة فيديو",
            ),
        ),
        migrations.AddField(
            model_name="adpackage",
            name="feature_auto_refresh_price",
            field=models.DecimalField(
                decimal_places=2,
                default=35,
                help_text="سعر إضافي لتفعيل التحديث التلقائي اليومي للإعلان",
                max_digits=10,
                verbose_name="سعر التحديث التلقائي",
            ),
        ),
        migrations.AddField(
            model_name="classifiedad",
            name="auto_refresh",
            field=models.BooleanField(
                default=False,
                help_text="تحديث تاريخ الإعلان تلقائياً كل يوم لمدة 7 أيام (ميزة مدفوعة)",
                verbose_name="تحديث تلقائي يومي",
            ),
        ),
    ]
