# Generated by Django 5.2.7 on 2026-03-26 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0051_safetytip"),
        ("main", "1003_fix_custom_field_labels"),
    ]

    operations = []
