# Generated by Django 5.2.7 on 2026-03-31 13:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1004_merge_0051_safetytip_1003_fix_custom_field_labels"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("welcome", "ترحيب - Welcome"),
                            (
                                "password_reset",
                                "إعادة تعيين كلمة المرور - Password Reset",
                            ),
                            (
                                "email_verification",
                                "تأكيد البريد الإلكتروني - Email Verification",
                            ),
                            ("otp_verification", "رمز التحقق - OTP Verification"),
                            ("ad_approved", "قبول الإعلان - Ad Approved"),
                            ("ad_rejected", "رفض الإعلان - Ad Rejected"),
                            ("order_created", "تأكيد الطلب - Order Created"),
                            (
                                "order_status_update",
                                "تحديث حالة الطلب - Order Status Update",
                            ),
                            (
                                "saved_search_notification",
                                "إشعار البحث المحفوظ - Saved Search Notification",
                            ),
                            (
                                "newsletter_confirmation",
                                "تأكيد النشرة البريدية - Newsletter Confirmation",
                            ),
                            ("contact_form", "نموذج التواصل - Contact Form"),
                            ("custom", "مخصص - Custom"),
                        ],
                        help_text="معرّف فريد يُستخدم في الكود لاستدعاء القالب / Unique identifier used in code to call this template",
                        max_length=60,
                        unique=True,
                        verbose_name="المفتاح - Key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        verbose_name="الاسم بالإنجليزية - Name (English)",
                    ),
                ),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="الاسم بالعربية - Name (Arabic)",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="موضوع الرسالة بالإنجليزية - Subject (English)",
                    ),
                ),
                (
                    "subject_ar",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="موضوع الرسالة بالعربية - Subject (Arabic)",
                    ),
                ),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        verbose_name="محتوى الرسالة بالإنجليزية - Body (English)",
                    ),
                ),
                (
                    "body_ar",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        verbose_name="محتوى الرسالة بالعربية - Body (Arabic)",
                    ),
                ),
                (
                    "available_variables",
                    models.TextField(
                        blank=True,
                        help_text="المتغيرات التي يمكن استخدامها في القالب، مثال: {{user_name}}, {{site_name}}\nVariables available in this template, e.g.: {{user_name}}, {{site_name}}",
                        verbose_name="المتغيرات المتاحة - Available Variables",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
            ],
            options={
                "verbose_name": "قالب بريد إلكتروني - Email Template",
                "verbose_name_plural": "قوالب البريد الإلكتروني - Email Templates",
                "db_table": "email_templates",
                "ordering": ["key"],
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(
                default="EGP",
                help_text="العملة المستخدمة للطلب",
                max_length=3,
                verbose_name="العملة - Currency",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(
                default="EGP", max_length=3, verbose_name="العملة - Currency"
            ),
        ),
    ]
