# Generated by Django 5.2.7 on 2026-04-07 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_add_paid_advertisement_model"),
        ("main", "1005_email_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaidAdvertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="عنوان الإعلان المدفوع",
                        max_length=200,
                        verbose_name="العنوان - Title",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان بالعربية"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="وصف مختصر للإعلان",
                        verbose_name="الوصف - Description",
                    ),
                ),
                (
                    "description_ar",
                    models.TextField(blank=True, verbose_name="الوصف بالعربية"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="اسم الشركة - Company Name",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="بريد التواصل - Contact Email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="هاتف التواصل - Contact Phone",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="الحجم الموصى به: 1200x600 بكسل للبانر، 300x600 للجانبي",
                        upload_to="paid_ads/%Y/%m/",
                        verbose_name="صورة الإعلان - Ad Image",
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="صورة مخصصة للأجهزة المحمولة (اختياري)",
                        null=True,
                        upload_to="paid_ads/%Y/%m/mobile/",
                        verbose_name="صورة الموبايل - Mobile Image",
                    ),
                ),
                (
                    "target_url",
                    models.URLField(
                        help_text="الرابط الذي سيتم توجيه المستخدم إليه عند النقر",
                        verbose_name="رابط الإعلان - Target URL",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="المزيد",
                        max_length=50,
                        verbose_name="نص زر الإجراء - CTA Button Text",
                    ),
                ),
                (
                    "cta_text_ar",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نص زر الإجراء بالعربية"
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=True, verbose_name="فتح في تبويب جديد - Open in New Tab"
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner", "بانر إعلاني - Banner"),
                            ("sidebar", "إعلان جانبي - Sidebar"),
                            ("popup", "نافذة منبثقة - Popup"),
                            ("featured_box", "صندوق مميز - Featured Box"),
                        ],
                        default="banner",
                        max_length=20,
                        verbose_name="نوع الإعلان - Ad Type",
                    ),
                ),
                (
                    "placement_type",
                    models.CharField(
                        choices=[
                            ("general", "عام (الصفحة الرئيسية) - General (Homepage)"),
                            ("category", "قسم محدد - Specific Category"),
                            ("subcategory", "قسم فرعي محدد - Specific Subcategory"),
                        ],
                        default="general",
                        help_text="حدد أين سيظهر الإعلان: الصفحة الرئيسية، قسم محدد، أو قسم فرعي",
                        max_length=20,
                        verbose_name="نوع الموضع - Placement Type",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="متى يبدأ عرض الإعلان",
                        verbose_name="تاريخ البدء - Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        help_text="متى ينتهي عرض الإعلان",
                        verbose_name="تاريخ الانتهاء - End Date",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "مسودة - Draft"),
                            ("active", "نشط - Active"),
                            ("paused", "متوقف مؤقتاً - Paused"),
                            ("expired", "منتهي - Expired"),
                            ("pending", "قيد المراجعة - Pending Approval"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="الحالة - Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="تفعيل/إيقاف الإعلان مؤقتاً",
                        verbose_name="نشط - Active",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="الإعلانات ذات الأولوية الأعلى تظهر أولاً (الأرقام الأكبر أولوية أعلى)",
                        verbose_name="الأولوية - Priority",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="ترتيب العرض ضمن نفس مستوى الأولوية",
                        verbose_name="الترتيب - Order",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="تكلفة الإعلان المدفوع",
                        max_digits=10,
                        verbose_name="السعر - Price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة - Currency"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "غير مدفوع - Unpaid"),
                            ("paid", "مدفوع - Paid"),
                            ("refunded", "مسترد - Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="حالة الدفع - Payment Status",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="مرجع الدفع - Payment Reference",
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد المشاهدات - Views Count"
                    ),
                ),
                (
                    "clicks_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد النقرات - Clicks Count"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, verbose_name="ملاحظات الإدارة - Admin Notes"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="تاريخ الموافقة - Approval Date",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_advertisements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المعلن - Advertiser",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_paid_ads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تمت الموافقة بواسطة - Approved By",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="اختر عدة أقسام لعرض هذا الإعلان فيها",
                        related_name="multi_paid_advertisements",
                        to="main.category",
                        verbose_name="أقسام متعددة - Multiple Categories",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="القسم الذي سيظهر فيه الإعلان (اختياري - للإعلانات المرتبطة بقسم)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_advertisements",
                        to="main.category",
                        verbose_name="القسم - Category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="الدولة التي سيظهر فيها الإعلان",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_advertisements",
                        to="content.country",
                        verbose_name="الدولة - Country",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        help_text="القسم الفرعي المحدد (اختياري)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_advertisements_subcategory",
                        to="main.category",
                        verbose_name="القسم الفرعي - Subcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعلان مدفوع - Paid Advertisement",
                "verbose_name_plural": "الإعلانات المدفوعة - Paid Advertisements",
                "db_table": "paid_advertisements",
                "ordering": ["-priority", "order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "is_active", "start_date", "end_date"],
                        name="paid_advert_status_eb72a9_idx",
                    ),
                    models.Index(
                        fields=["country", "placement_type"],
                        name="paid_advert_country_c81663_idx",
                    ),
                    models.Index(
                        fields=["category", "is_active"],
                        name="paid_advert_categor_572737_idx",
                    ),
                    models.Index(
                        fields=["-priority", "order"],
                        name="paid_advert_priorit_1b732a_idx",
                    ),
                ],
            },
        ),
    ]
