# Generated by Django 5.2.7 on 2026-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1006_add_paid_advertisement_model"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adimage",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "Ad Image",
                "verbose_name_plural": "Ad Images",
            },
        ),
        migrations.AddField(
            model_name="paidadvertisement",
            name="advertising_space",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="معرف المساحة الإعلانية - يمكن لعدة معلنين شراء نفس المساحة وسيتم عرضهم بالتناوب",
                max_length=100,
                null=True,
                verbose_name="المساحة الإعلانية - Advertising Space",
            ),
        ),
    ]
