# Generated by Django 5.2.7 on 2026-04-18 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_add_paid_advertisement_model"),
        ("main", "1008_rename_paid_advertisement_to_paid_banner"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannerPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner", "بانر إعلاني - Banner"),
                            ("sidebar", "إعلان جانبي - Sidebar"),
                            ("popup", "نافذة منبثقة - Popup"),
                            ("featured_box", "صندوق مميز - Featured Box"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإعلان - Ad Type",
                    ),
                ),
                (
                    "placement_type",
                    models.CharField(
                        choices=[
                            ("general", "عام (الصفحة الرئيسية) - General (Homepage)"),
                            ("category", "قسم محدد - Specific Category"),
                            ("subcategory", "قسم فرعي محدد - Specific Subcategory"),
                        ],
                        max_length=20,
                        verbose_name="نوع الموضع - Placement Type",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="السعر لهذا النوع من الإعلان في هذا الموضع",
                        max_digits=10,
                        verbose_name="السعر - Price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EGP", max_length=3, verbose_name="العملة - Currency"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "تسعير البنر - Banner Pricing",
                "verbose_name_plural": "تسعيرات البنرات - Banner Pricing",
                "db_table": "banner_pricing",
                "ordering": ["ad_type", "placement_type"],
            },
        ),
        migrations.RenameIndex(
            model_name="paidbanner",
            new_name="paid_banner_status_24b874_idx",
            old_name="paid_advert_status_eb72a9_idx",
        ),
        migrations.RenameIndex(
            model_name="paidbanner",
            new_name="paid_banner_country_b4a1ef_idx",
            old_name="paid_advert_country_c81663_idx",
        ),
        migrations.RenameIndex(
            model_name="paidbanner",
            new_name="paid_banner_categor_793a9a_idx",
            old_name="paid_advert_categor_572737_idx",
        ),
        migrations.RenameIndex(
            model_name="paidbanner",
            new_name="paid_banner_priorit_73ed93_idx",
            old_name="paid_advert_priorit_1b732a_idx",
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="advertiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_banners",
                to=settings.AUTH_USER_MODEL,
                verbose_name="المعلن - Advertiser",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="اختر عدة أقسام لعرض هذا الإعلان فيها",
                related_name="multi_paid_banners",
                to="main.category",
                verbose_name="أقسام متعددة - Multiple Categories",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="القسم الذي سيظهر فيه الإعلان (اختياري - للإعلانات المرتبطة بقسم)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_banners",
                to="main.category",
                verbose_name="القسم - Category",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="country",
            field=models.ForeignKey(
                help_text="الدولة التي سيظهر فيها الإعلان",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_banners",
                to="content.country",
                verbose_name="الدولة - Country",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="image",
            field=models.ImageField(
                help_text="المقاسات المعيارية: بانر (Leaderboard) 728×90 | جانبي (Medium Rectangle) 300×250 | مميز (Billboard) 970×250",
                upload_to="paid_ads/%Y/%m/",
                verbose_name="صورة الإعلان - Ad Image",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="صورة للموبايل (اختياري) - المقاس المعياري: Mobile Banner 320×50",
                null=True,
                upload_to="paid_ads/%Y/%m/mobile/",
                verbose_name="صورة الموبايل - Mobile Image",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                help_text="القسم الفرعي المحدد (اختياري)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_banners_subcategory",
                to="main.category",
                verbose_name="القسم الفرعي - Subcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="bannerpricing",
            index=models.Index(
                fields=["ad_type", "placement_type", "is_active"],
                name="banner_pric_ad_type_bbba00_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bannerpricing",
            unique_together={("ad_type", "placement_type")},
        ),
    ]
