# Generated by Django 5.2.7 on 2026-04-18 11:33

from decimal import Decimal
from django.db import migrations


def populate_banner_pricing(apps, schema_editor):
    """Populate BannerPricing table with default prices"""
    BannerPricing = apps.get_model('main', 'BannerPricing')

    # Define pricing structure: (ad_type, placement_type, price)
    pricing_data = [
        # Banner prices
        ('banner', 'general', Decimal('200.00')),       # Homepage banner - highest traffic
        ('banner', 'category', Decimal('150.00')),      # Category banner - targeted
        ('banner', 'subcategory', Decimal('120.00')),   # Subcategory banner - very targeted

        # Sidebar prices
        ('sidebar', 'general', Decimal('150.00')),      # Homepage sidebar
        ('sidebar', 'category', Decimal('120.00')),     # Category sidebar
        ('sidebar', 'subcategory', Decimal('100.00')),  # Subcategory sidebar

        # Popup prices (highest engagement)
        ('popup', 'general', Decimal('250.00')),        # Homepage popup
        ('popup', 'category', Decimal('200.00')),       # Category popup
        ('popup', 'subcategory', Decimal('180.00')),    # Subcategory popup

        # Featured box prices
        ('featured_box', 'general', Decimal('180.00')),      # Homepage featured
        ('featured_box', 'category', Decimal('140.00')),     # Category featured
        ('featured_box', 'subcategory', Decimal('110.00')),  # Subcategory featured
    ]

    # Create pricing records
    for ad_type, placement_type, price in pricing_data:
        BannerPricing.objects.get_or_create(
            ad_type=ad_type,
            placement_type=placement_type,
            defaults={
                'price': price,
                'currency': 'EGP',
                'is_active': True,
            }
        )


def reverse_populate(apps, schema_editor):
    """Remove all pricing data"""
    BannerPricing = apps.get_model('main', 'BannerPricing')
    BannerPricing.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1009_add_banner_pricing_model"),
    ]

    operations = [
        migrations.RunPython(populate_banner_pricing, reverse_populate),
    ]
