# Generated by Django 5.2.7 on 2026-04-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_add_paid_advertisement_model"),
        ("main", "1010_populate_banner_pricing"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdSenseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_type",
                    models.CharField(
                        choices=[
                            ("banner", "بانر إعلاني - Banner"),
                            ("sidebar", "إعلان جانبي - Sidebar"),
                            ("popup", "نافذة منبثقة - Popup"),
                            ("featured_box", "صندوق مميز - Featured Box"),
                        ],
                        help_text="نوع البنر الذي سيُعرض فيه إعلان AdSense عند غياب إعلان مدفوع",
                        max_length=20,
                        unique=True,
                        verbose_name="نوع البنر - Banner Type",
                    ),
                ),
                (
                    "ad_client",
                    models.CharField(
                        help_text="مثال: ca-pub-1234567890123456",
                        max_length=60,
                        verbose_name="معرف الناشر - Ad Client",
                    ),
                ),
                (
                    "ad_slot",
                    models.CharField(
                        help_text="مثال: 1234567890",
                        max_length=20,
                        verbose_name="معرف الإعلان - Ad Slot",
                    ),
                ),
                (
                    "ad_format",
                    models.CharField(
                        choices=[
                            ("auto", "تلقائي - Auto"),
                            ("rectangle", "مستطيل - Rectangle"),
                            ("horizontal", "أفقي - Horizontal"),
                            ("vertical", "عمودي - Vertical"),
                        ],
                        default="auto",
                        max_length=20,
                        verbose_name="تنسيق الإعلان - Ad Format",
                    ),
                ),
                (
                    "full_width_responsive",
                    models.BooleanField(
                        default=True,
                        verbose_name="استجابة كاملة للعرض - Full Width Responsive",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
            ],
            options={
                "verbose_name": "إعداد AdSense - AdSense Config",
                "verbose_name_plural": "إعدادات AdSense - AdSense Configs",
                "db_table": "adsense_config",
                "ordering": ["ad_type"],
            },
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="image",
            field=models.ImageField(
                help_text="المقاس حسب النوع: بانر 728×90 | جانبي/نافذة 300×250 | مميز 970×250 — سيتم رفض الصورة إذا كانت الأبعاد مختلفة",
                upload_to="paid_ads/%Y/%m/",
                verbose_name="صورة الإعلان - Ad Image",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="إجبارية لنوع 'بانر إعلاني' — المقاس المطلوب: Mobile Banner 320×50 بكسل",
                null=True,
                upload_to="paid_ads/%Y/%m/mobile/",
                verbose_name="صورة الموبايل - Mobile Image",
            ),
        ),
        migrations.CreateModel(
            name="AdSenseSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_key",
                    models.CharField(
                        choices=[
                            ("home_banner", "الصفحة الرئيسية — بانر (728×90)"),
                            ("home_sidebar", "الصفحة الرئيسية — جانبي (300×250)"),
                            ("home_featured", "الصفحة الرئيسية — مميز (970×250)"),
                            ("category_banner", "صفحة القسم — بانر (728×90)"),
                            ("category_sidebar", "صفحة القسم — جانبي (300×250)"),
                            ("category_featured", "صفحة القسم — مميز (970×250)"),
                        ],
                        help_text="الموضع الذي سيستبدله AdSense — كل دولة يمكن أن يكون لها إعداد مختلف",
                        max_length=30,
                        verbose_name="موضع الإعلان",
                    ),
                ),
                (
                    "ad_client",
                    models.CharField(
                        help_text="مثال: ca-pub-1234567890123456",
                        max_length=60,
                        verbose_name="Ad Client",
                    ),
                ),
                (
                    "ad_slot",
                    models.CharField(
                        help_text="رقم الـ slot من لوحة Google AdSense",
                        max_length=20,
                        verbose_name="Ad Slot ID",
                    ),
                ),
                (
                    "ad_format",
                    models.CharField(
                        choices=[
                            ("auto", "Auto (تلقائي)"),
                            ("rectangle", "Rectangle (مستطيل)"),
                            ("horizontal", "Horizontal (أفقي)"),
                            ("vertical", "Vertical (رأسي)"),
                        ],
                        default="auto",
                        max_length=15,
                        verbose_name="تنسيق الإعلان",
                    ),
                ),
                (
                    "is_responsive",
                    models.BooleanField(
                        default=True,
                        help_text="data-full-width-responsive — يجعل الإعلان يتكيف مع عرض الشاشة",
                        verbose_name="responsive",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="إذا كان غير نشط، سيظهر البانر المدفوع بدلاً منه",
                        verbose_name="نشط",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        help_text="اعرض هذا الإعلان لزوار هذه الدولة فقط",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="content.country",
                        verbose_name="الدولة",
                    ),
                ),
            ],
            options={
                "verbose_name": "إعداد AdSense",
                "verbose_name_plural": "إعدادات AdSense",
                "ordering": ["slot_key", "country"],
                "unique_together": {("slot_key", "country")},
            },
        ),
    ]
