# Generated by Django 5.2.7 on 2026-04-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1011_add_adsense_slot_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AdSenseConfig",
        ),
    ]
