# Generated by Django 5.2.7 on 2026-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1012_remove_adsense_config_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdvertisingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "إدارة الإعلانات",
                "verbose_name_plural": "إدارة الإعلانات",
                "managed": False,
            },
        ),
    ]
