# Generated by Django 5.2.7 on 2026-04-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1013_add_advertising_config_proxy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerpricing",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="سعر اليوم الواحد لهذا النوع من الإعلان في هذا الموضع",
                max_digits=10,
                verbose_name="السعر اليومي - Daily Price",
            ),
        ),
    ]
