# Generated by Django 5.2.7 on 2026-05-02 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_add_paid_advertisement_model"),
        ("main", "1014_alter_bannerpricing_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidbanner",
            name="extra_countries",
            field=models.ManyToManyField(
                blank=True,
                help_text="دول إضافية لعرض الإعلان فيها مقابل رسوم إضافية لكل دولة",
                related_name="extra_paid_banners",
                to="content.country",
                verbose_name="دول إضافية - Extra Countries",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="country",
            field=models.ForeignKey(
                help_text="الدولة الأساسية التي سيظهر فيها الإعلان",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paid_banners",
                to="content.country",
                verbose_name="الدولة - Country",
            ),
        ),
    ]
