# Generated by Django 5.2.7 on 2026-05-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1015_paid_banner_extra_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("general", "عام"),
                    ("ad_approved", "الإعلان معتمد"),
                    ("ad_rejected", "الإعلان مرفوض"),
                    ("ad_expired", "الإعلان منتهي"),
                    ("package_expired", "الباقة منتهية"),
                    ("saved_search", "نتائج البحث المحفوظ"),
                    ("facebook_share_rejected", "طلب مشاركة فيسبوك مرفوض"),
                    ("admin_facebook_pending", "طلب مشاركة فيسبوك معلق للمراجعة"),
                ],
                max_length=30,
            ),
        ),
    ]
