# Generated by Django 5.2.7 on 2026-05-21 14:02

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1016_widen_notification_type_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="العنوان بالإنجليزية"
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان بالعربية"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        help_text="مثال: about-us → سيظهر على /pages/about-us/",
                        max_length=120,
                        unique=True,
                        verbose_name="الرابط (slug)",
                    ),
                ),
                (
                    "body",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="المحتوى بالإنجليزية"
                    ),
                ),
                (
                    "body_ar",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="المحتوى بالعربية"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="وصف SEO بالإنجليزية"
                    ),
                ),
                (
                    "meta_description_ar",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="وصف SEO بالعربية"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
                (
                    "show_in_navbar",
                    models.BooleanField(
                        default=False, verbose_name="إظهار في شريط التنقل"
                    ),
                ),
                (
                    "navbar_order",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="ترتيب في الشريط"
                    ),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(default=False, verbose_name="إظهار في التذييل"),
                ),
                (
                    "footer_order",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="ترتيب في التذييل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
            ],
            options={
                "verbose_name": "صفحة مخصصة",
                "verbose_name_plural": "الصفحات المخصصة",
                "db_table": "custom_pages",
                "ordering": ["navbar_order", "title"],
            },
        ),
    ]
