# Generated by Django 5.2.7 on 2026-05-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1017_add_custom_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adfeature",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("pinned", "تثبيت - Pinned"),
                    ("top_search", "أعلى نتائج البحث - Top Search"),
                    ("featured_section", "قسم مميز - Featured Section"),
                    ("video", "إضافة فيديو - Video (قيد التطوير)"),
                    ("contact_for_price", "تواصل ليصلك عرض سعر - Contact for Price"),
                    ("facebook_share", "نشر على فيسبوك - Facebook Share"),
                    ("urgent", "إعلان عاجل - Urgent"),
                    ("auto_refresh", "تحديث تلقائي - Auto Refresh"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="adfeatureprice",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("pinned", "تثبيت - Pinned"),
                    ("top_search", "أعلى نتائج البحث - Top Search"),
                    ("featured_section", "قسم مميز - Featured Section"),
                    ("video", "إضافة فيديو - Video (قيد التطوير)"),
                    ("contact_for_price", "تواصل ليصلك عرض سعر - Contact for Price"),
                    ("facebook_share", "نشر على فيسبوك - Facebook Share"),
                    ("urgent", "إعلان عاجل - Urgent"),
                    ("auto_refresh", "تحديث تلقائي - Auto Refresh"),
                ],
                max_length=20,
                verbose_name="نوع الميزة",
            ),
        ),
    ]
