# Generated by Django 5.2.7 on 2026-05-23 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1019_fix_invalid_profile_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("order_created", "تأكيد الطلب - Order Created"),
                            ("order_shipped", "تم الشحن - Order Shipped"),
                            ("order_delivered", "تم التسليم - Order Delivered"),
                            ("order_cancelled", "إلغاء الطلب - Order Cancelled"),
                            ("order_paid", "تأكيد الدفع - Payment Confirmed"),
                            ("order_partial_payment", "دفعة جزئية - Partial Payment"),
                        ],
                        help_text="معرّف فريد يُستخدم في الكود لاستدعاء القالب",
                        max_length=60,
                        unique=True,
                        verbose_name="المفتاح - Key",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="الاسم - Name")),
                (
                    "name_ar",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="الاسم بالعربية - Name (Arabic)",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="نص رسالة SMS. استخدم {{variable}} للمتغيرات، مثال: {{order_number}}، {{site_name}}",
                        verbose_name="نص الرسالة - Message Body",
                    ),
                ),
                (
                    "available_variables",
                    models.TextField(
                        blank=True,
                        help_text="المتغيرات التي يمكن استخدامها في القالب، مثال: {{order_number}}, {{site_name}}",
                        verbose_name="المتغيرات المتاحة - Available Variables",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="نشط - Active"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل"),
                ),
            ],
            options={
                "verbose_name": "قالب رسالة SMS - SMS Template",
                "verbose_name_plural": "قوالب رسائل SMS - SMS Templates",
                "db_table": "sms_templates",
                "ordering": ["key"],
            },
        ),
    ]
