# Generated by Django 5.2.14 on 2026-05-23 23:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1020_add_sms_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="رمز الخصم"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "نسبة مئوية"), ("fixed", "مبلغ ثابت")],
                        default="percentage",
                        max_length=20,
                        verbose_name="نوع الخصم",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="قيمة الخصم"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="الحد الأدنى للطلب",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="الحد الأقصى للاستخدام"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="عدد الاستخدامات"
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="صالح من")),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="صالح حتى"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "كوبون خصم",
                "verbose_name_plural": "كوبونات الخصم",
                "db_table": "coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="مبلغ الخصم",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="main.coupon",
                verbose_name="كوبون الخصم",
            ),
        ),
    ]
