# Generated by Django 5.2.14 on 2026-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1023_add_banner_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paidbanner",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "غير مدفوع - Unpaid"),
                    ("receipt_submitted", "إيصال مقدم - Receipt Submitted"),
                    ("paid", "مدفوع - Paid"),
                    ("refunded", "مسترد - Refunded"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="حالة الدفع - Payment Status",
            ),
        ),
    ]
