# Generated by Django 5.2.14 on 2026-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1024_alter_paidbanner_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bannerslot",
            name="ad_type",
            field=models.CharField(
                choices=[
                    ("banner", "بانر إعلاني (1200×150)"),
                    ("sidebar", "إعلان جانبي (300×250)"),
                    ("featured_box", "صندوق مميز (1200×250)"),
                ],
                default="banner",
                max_length=20,
                verbose_name="نوع البانر",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                help_text="يُحسب تلقائياً: تاريخ التفعيل + مدة الإعلان",
                null=True,
                verbose_name="تاريخ الانتهاء - End Date",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="image",
            field=models.ImageField(
                help_text="المقاس حسب النوع: بانر 1200×150 | جانبي/نافذة 300×250 | مميز 1200×250 — سيتم رفض الصورة إذا كانت الأبعاد مختلفة",
                upload_to="paid_ads/%Y/%m/",
                verbose_name="صورة الإعلان - Ad Image",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                help_text="يُحدَّد تلقائياً عند تفعيل الإعلان من الإدارة",
                null=True,
                verbose_name="تاريخ البدء - Start Date",
            ),
        ),
    ]
