# Generated by Django 5.2.14 on 2026-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1025_paidbanner_duration_days_nullable_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="paidbanner",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="عدد الأيام التي سيعرض فيها الإعلان بعد تفعيله من الإدارة",
                verbose_name="مدة الإعلان بالأيام - Duration (days)",
            ),
        ),
    ]
