# Generated by Django 5.2.14 on 2026-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1026_paidbanner_duration_days"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "رسالة تواصل",
                "verbose_name_plural": "رسائل التواصل",
            },
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paypal", "PayPal"),
                    ("paymob", "Paymob"),
                    ("instapay", "إنستا باي - InstaPay"),
                    ("wallet", "محفظة إلكترونية - Wallet"),
                    ("bank_transfer", "تحويل بنكي - Bank Transfer"),
                    ("cod", "الدفع عند الاستلام - Cash on Delivery"),
                    ("cash", "نقداً - Cash"),
                ],
                default="",
                max_length=20,
                verbose_name="مزود الدفع - Payment Provider",
            ),
        ),
    ]
