# Generated by Django 5.2.14 on 2026-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1027_payment_provider_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifiedad",
            name="city_en",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="المدينة (إنجليزي)"
            ),
        ),
        migrations.AlterField(
            model_name="classifiedad",
            name="city",
            field=models.CharField(max_length=100, verbose_name="المدينة (عربي)"),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="key",
            field=models.CharField(
                choices=[
                    ("welcome", "ترحيب - Welcome"),
                    ("password_reset", "إعادة تعيين كلمة المرور - Password Reset"),
                    (
                        "email_verification",
                        "تأكيد البريد الإلكتروني - Email Verification",
                    ),
                    ("otp_verification", "رمز التحقق - OTP Verification"),
                    ("ad_approved", "قبول الإعلان - Ad Approved"),
                    ("ad_rejected", "رفض الإعلان - Ad Rejected"),
                    ("ad_created", "إنشاء إعلان جديد - Ad Created"),
                    ("order_created", "تأكيد الطلب - Order Created"),
                    ("order_status_update", "تحديث حالة الطلب - Order Status Update"),
                    ("package_activated", "تفعيل الباقة - Package Activated"),
                    (
                        "saved_search_notification",
                        "إشعار البحث المحفوظ - Saved Search Notification",
                    ),
                    (
                        "newsletter_confirmation",
                        "تأكيد النشرة البريدية - Newsletter Confirmation",
                    ),
                    ("contact_form", "نموذج التواصل - Contact Form"),
                    ("new_message", "رسالة جديدة - New Chat Message"),
                    ("custom", "مخصص - Custom"),
                ],
                help_text="معرّف فريد يُستخدم في الكود لاستدعاء القالب / Unique identifier used in code to call this template",
                max_length=60,
                unique=True,
                verbose_name="المفتاح - Key",
            ),
        ),
    ]
