# Generated by Django 5.2.14 on 2026-06-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "1028_add_city_en_to_classified_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adsenseslot",
            name="slot_key",
            field=models.CharField(
                choices=[
                    ("home_banner", "الصفحة الرئيسية — بانر (970×150)"),
                    ("home_sidebar", "الصفحة الرئيسية — جانبي (300×250)"),
                    ("home_featured", "الصفحة الرئيسية — مميز (970×250)"),
                    ("category_banner", "صفحة القسم — بانر (970×150)"),
                    ("category_sidebar", "صفحة القسم — جانبي (300×250)"),
                    ("category_featured", "صفحة القسم — مميز (970×250)"),
                ],
                help_text="الموضع الذي سيستبدله AdSense — كل دولة يمكن أن يكون لها إعداد مختلف",
                max_length=30,
                verbose_name="موضع الإعلان",
            ),
        ),
        migrations.AlterField(
            model_name="bannerslot",
            name="ad_type",
            field=models.CharField(
                choices=[
                    ("banner", "بانر إعلاني (970×150)"),
                    ("sidebar", "إعلان جانبي (300×250)"),
                    ("featured_box", "صندوق مميز (970×250)"),
                ],
                default="banner",
                max_length=20,
                verbose_name="نوع البانر",
            ),
        ),
        migrations.AlterField(
            model_name="paidbanner",
            name="image",
            field=models.ImageField(
                help_text="المقاس حسب النوع: بانر 970×150 | جانبي/نافذة 300×250 | مميز 970×250 — سيتم رفض الصورة إذا كانت الأبعاد مختلفة",
                upload_to="paid_ads/%Y/%m/",
                verbose_name="صورة الإعلان - Ad Image",
            ),
        ),
    ]
