# Generated by Django 5.2.7 on 2025-10-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدولة')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Country Name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='كود الدولة')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='علم الدولة')),
                ('phone_code', models.CharField(blank=True, max_length=10, verbose_name='كود الهاتف')),
                ('currency', models.CharField(blank=True, max_length=10, verbose_name='العملة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دولة',
                'verbose_name_plural': 'الدول',
                'ordering': ['order', 'name'],
            },
        ),
    ]
