# Generated by Django 5.2.7 on 2025-11-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("content", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="blogs/")),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["created_on"],
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="اسم الدولة")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="كود الدولة"
                    ),
                ),
                (
                    "flag_emoji",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="علم الدولة"
                    ),
                ),
                (
                    "phone_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="كود الهاتف"
                    ),
                ),
                (
                    "currency",
                    models.CharField(blank=True, max_length=10, verbose_name="العملة"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "دولة",
                "verbose_name_plural": "الدول",
                "ordering": ["order", "name"],
            },
        ),
    ]
