# Generated by Django 5.2.7 on 2025-11-26 19:57

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
