# Generated by Django 5.2.7 on 2025-11-30 17:07

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_blog_content_alter_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200, verbose_name='العنوان - Title')),
                ('title_ar', models.CharField(default='من نحن', max_length=200, verbose_name='العنوان بالعربية')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='المحتوى - Content')),
                ('content_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='المحتوى بالعربية')),
                ('mission', models.TextField(blank=True, verbose_name='رسالتنا - Mission')),
                ('mission_ar', models.TextField(blank=True, verbose_name='رسالتنا بالعربية')),
                ('vision', models.TextField(blank=True, verbose_name='رؤيتنا - Vision')),
                ('vision_ar', models.TextField(blank=True, verbose_name='رؤيتنا بالعربية')),
                ('values', models.TextField(blank=True, verbose_name='قيمنا - Values')),
                ('values_ar', models.TextField(blank=True, verbose_name='قيمنا بالعربية')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='صورة مميزة')),
            ],
            options={
                'verbose_name': 'صفحة من نحن',
                'verbose_name_plural': 'صفحة من نحن',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Contact Us', max_length=200, verbose_name='العنوان - Title')),
                ('title_ar', models.CharField(default='اتصل بنا', max_length=200, verbose_name='العنوان بالعربية')),
                ('description', models.TextField(blank=True, verbose_name='الوصف - Description')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('enable_contact_form', models.BooleanField(default=True, verbose_name='تفعيل نموذج التواصل')),
                ('notification_email', models.EmailField(blank=True, help_text='البريد الذي سيتم إرسال رسائل التواصل إليه', max_length=254, verbose_name='البريد الإلكتروني لاستقبال الرسائل')),
                ('office_hours', models.TextField(blank=True, verbose_name='ساعات العمل - Office Hours')),
                ('office_hours_ar', models.TextField(blank=True, verbose_name='ساعات العمل بالعربية')),
                ('map_embed_code', models.TextField(blank=True, help_text='كود HTML من Google Maps', verbose_name='كود الخريطة - Map Embed Code')),
            ],
            options={
                'verbose_name': 'صفحة اتصل بنا',
                'verbose_name_plural': 'صفحة اتصل بنا',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Idrissimart', max_length=200, verbose_name='عنوان البطل - Hero Title')),
                ('hero_title_ar', models.CharField(default='مرحباً بك في إدريسي مارت', max_length=200, verbose_name='عنوان البطل بالعربية')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='العنوان الفرعي - Subtitle')),
                ('hero_subtitle_ar', models.TextField(blank=True, verbose_name='العنوان الفرعي بالعربية')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/', verbose_name='صورة البطل - Hero Image')),
                ('hero_button_text', models.CharField(default='Get Started', max_length=100, verbose_name='نص الزر - Button Text')),
                ('hero_button_text_ar', models.CharField(default='ابدأ الآن', max_length=100, verbose_name='نص الزر بالعربية')),
                ('hero_button_url', models.CharField(default='/ads/', max_length=200, verbose_name='رابط الزر - Button URL')),
                ('show_modal', models.BooleanField(default=False, help_text='عرض نافذة منبثقة عند زيارة الصفحة الرئيسية', verbose_name='إظهار نافذة الإعلان')),
                ('modal_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الإعلان - Modal Title')),
                ('modal_title_ar', models.CharField(blank=True, max_length=200, verbose_name='عنوان الإعلان بالعربية')),
                ('modal_content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='محتوى الإعلان - Modal Content')),
                ('modal_content_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='محتوى الإعلان بالعربية')),
                ('modal_image', models.ImageField(blank=True, null=True, upload_to='homepage/modal/', verbose_name='صورة الإعلان')),
                ('modal_button_text', models.CharField(blank=True, max_length=100, verbose_name='نص زر الإعلان')),
                ('modal_button_text_ar', models.CharField(blank=True, max_length=100, verbose_name='نص زر الإعلان بالعربية')),
                ('modal_button_url', models.CharField(blank=True, max_length=200, verbose_name='رابط زر الإعلان')),
                ('show_featured_categories', models.BooleanField(default=True, verbose_name='عرض الأقسام المميزة')),
                ('show_featured_ads', models.BooleanField(default=True, verbose_name='عرض الإعلانات المميزة')),
            ],
            options={
                'verbose_name': 'محتوى الصفحة الرئيسية',
                'verbose_name_plural': 'محتوى الصفحة الرئيسية',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='إدريسي مارت', max_length=200, verbose_name='اسم الموقع - Site Name')),
                ('site_name_ar', models.CharField(default='إدريسي مارت', max_length=200, verbose_name='اسم الموقع بالعربية')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف الموقع - Site Description')),
                ('site_description_ar', models.TextField(blank=True, verbose_name='وصف الموقع بالعربية')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني للتواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='رقم الهاتف للتواصل')),
                ('contact_address', models.TextField(blank=True, verbose_name='العنوان')),
                ('contact_address_ar', models.TextField(blank=True, verbose_name='العنوان بالعربية')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('instagram_url', models.URLField(blank=True, verbose_name='رابط انستغرام')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط لينكد إن')),
                ('whatsapp_number', models.CharField(blank=True, max_length=50, verbose_name='رقم واتساب')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
    ]
