# Generated by Django 5.2.7 on 2025-11-30 17:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_aboutpage_contactpage_homepage_siteconfiguration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_address_ar',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_description_ar',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='site_name_ar',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='copyright_text',
            field=models.CharField(default='© 2024 إدريسي مارت. جميع الحقوق محفوظة.', max_length=200, verbose_name='نص حقوق النشر'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='نص التذييل - Footer Text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='نص التذييل بالعربية'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, verbose_name='الكلمات المفتاحية - Meta Keywords'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_keywords_ar',
            field=models.CharField(blank=True, max_length=500, verbose_name='الكلمات المفتاحية بالعربية'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='رسالتنا - Mission'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='رسالتنا بالعربية'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='قيمنا - Values'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='values_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='قيمنا بالعربية'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='رؤيتنا - Vision'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='رؤيتنا بالعربية'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='الوصف - Description'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='description_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='الوصف بالعربية'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='office_hours',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='ساعات العمل - Office Hours'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='office_hours_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='ساعات العمل بالعربية'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='العنوان الفرعي - Subtitle'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_subtitle_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='العنوان الفرعي بالعربية'),
        ),
    ]
