# Generated by Django 5.2.7 on 2025-11-30 17:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_siteconfiguration_contact_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200, verbose_name='العنوان - Title')),
                ('title_ar', models.CharField(default='سياسة الخصوصية', max_length=200, verbose_name='العنوان بالعربية')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='المحتوى - Content')),
                ('content_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='المحتوى بالعربية')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'صفحة سياسة الخصوصية',
                'verbose_name_plural': 'صفحة سياسة الخصوصية',
            },
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms and Conditions', max_length=200, verbose_name='العنوان - Title')),
                ('title_ar', models.CharField(default='الشروط والأحكام', max_length=200, verbose_name='العنوان بالعربية')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='المحتوى - Content')),
                ('content_ar', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='المحتوى بالعربية')),
                ('last_updated', models.DateField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'صفحة الشروط والأحكام',
                'verbose_name_plural': 'صفحة الشروط والأحكام',
            },
        ),
    ]
