# Generated by Django 5.2.7 on 2025-11-30 18:25

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_privacypage_termspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='map_embed_code',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='كود HTML من Google Maps', verbose_name='كود الخريطة - Map Embed Code'),
        ),
    ]
