# Generated by Django 5.2.7 on 2025-12-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_migrate_hero_to_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslider',
            name='country',
            field=models.ForeignKey(blank=True, help_text='اختر الدولة التي سيظهر فيها هذا السلايدر', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_sliders', to='content.country', verbose_name='الدولة - Country'),
        ),
    ]
