# Generated by Django 5.2.7 on 2025-12-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_add_country_to_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='show_address',
            field=models.BooleanField(default=True, help_text='إظهار أو إخفاء بطاقة معلومات العنوان', verbose_name='إظهار بطاقة العنوان'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_map',
            field=models.BooleanField(default=True, help_text='إظهار أو إخفاء قسم الخريطة', verbose_name='إظهار الخريطة'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_office_hours',
            field=models.BooleanField(default=True, help_text='إظهار أو إخفاء بطاقة ساعات العمل', verbose_name='إظهار بطاقة ساعات العمل'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='show_phone',
            field=models.BooleanField(default=True, help_text='إظهار أو إخفاء بطاقة معلومات الهاتف', verbose_name='إظهار بطاقة الهاتف'),
        ),
    ]
