# Generated by Django 5.2.7 on 2025-12-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_blogcategory_blog_views_count_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='cities',
            field=models.JSONField(blank=True, default=list, verbose_name='المدن'),
        ),
    ]
