# Generated by Django 5.2.7 on 2025-12-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_add_cities_to_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_email_verification',
            field=models.BooleanField(default=False, help_text='إذا كان مفعلاً، يجب على المستخدمين تأكيد بريدهم الإلكتروني أثناء التسجيل', verbose_name='التحقق من البريد الإلكتروني إلزامي'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_phone_verification',
            field=models.BooleanField(default=False, help_text='إذا كان مفعلاً، يجب على المستخدمين تأكيد رقم هاتفهم أثناء التسجيل', verbose_name='التحقق من رقم الهاتف إلزامي'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_verification_for_services',
            field=models.BooleanField(default=False, help_text='إذا كان مفعلاً، يجب التحقق من الحساب لاستخدام خدمات الموقع (نشر إعلانات، إضافة للسلة، إلخ)', verbose_name='التحقق مطلوب لاستخدام الخدمات'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='verification_services_message',
            field=models.TextField(default='يجب التحقق من حسابك لاستخدام هذه الخدمة', help_text='الرسالة التي تظهر للمستخدمين غير المتحققين عند محاولة استخدام الخدمات', verbose_name='رسالة التحقق للخدمات'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='verification_services_message_ar',
            field=models.TextField(default='يجب التحقق من حسابك لاستخدام هذه الخدمة', verbose_name='رسالة التحقق للخدمات بالعربية'),
        ),
    ]
