# Generated by Django 5.2.7 on 2025-12-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_siteconfiguration_require_email_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='instapay_qr_code',
            field=models.ImageField(blank=True, help_text='قم برفع صورة رمز QR الخاص بحساب InstaPay للدفع غير المتصل بالإنترنت', null=True, upload_to='payment/instapay/', verbose_name='رمز QR لـ InstaPay'),
        ),
    ]
