# Generated by Django 5.2.7 on 2025-12-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_add_instapay_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_offline_payment',
            field=models.BooleanField(default=True, help_text='تفعيل/تعطيل الدفع اليدوي عبر InstaPay أو المحفظة', verbose_name='السماح بالدفع اليدوي'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='allow_online_payment',
            field=models.BooleanField(default=True, help_text='تفعيل/تعطيل طرق الدفع الإلكتروني (PayMob, etc.)', verbose_name='السماح بالدفع الإلكتروني'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='instapay_phone',
            field=models.CharField(blank=True, help_text='رقم الهاتف المسجل في InstaPay', max_length=20, verbose_name='رقم هاتف InstaPay'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='offline_payment_instructions',
            field=models.TextField(blank=True, help_text='تعليمات للعملاء حول كيفية إتمام الدفع اليدوي', verbose_name='تعليمات الدفع اليدوي'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='offline_payment_instructions_ar',
            field=models.TextField(blank=True, default='1. قم بمسح رمز QR أو استخدم رابط المحفظة\n2. أرسل المبلغ المطلوب\n3. احتفظ بإيصال التحويل\n4. سيتم تفعيل الخدمة خلال 24 ساعة', verbose_name='تعليمات الدفع اليدوي بالعربية'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='wallet_payment_link',
            field=models.URLField(blank=True, help_text='رابط للدفع عبر المحفظة الإلكترونية (Vodafone Cash, Orange Money, etc.)', max_length=500, verbose_name='رابط المحفظة الإلكترونية'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='wallet_phone',
            field=models.CharField(blank=True, help_text='رقم الهاتف المسجل في المحفظة', max_length=20, verbose_name='رقم المحفظة الإلكترونية'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='instapay_qr_code',
            field=models.ImageField(blank=True, help_text='قم برفع صورة رمز QR الخاص بحساب InstaPay للدفع اليدوي', null=True, upload_to='payment/instapay/', verbose_name='رمز QR لـ InstaPay'),
        ),
    ]
