# Generated by Django 5.2.7 on 2025-12-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_siteconfiguration_allow_offline_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='ad_base_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='رسوم نشر إعلان عادي (0 = مجاني)', max_digits=10, verbose_name='رسوم نشر الإعلان الأساسية'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='featured_ad_price',
            field=models.DecimalField(decimal_places=2, default=50, help_text='رسوم جعل الإعلان مميزاً (Highlighted)', max_digits=10, verbose_name='سعر الإعلان المميز'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pinned_ad_price',
            field=models.DecimalField(decimal_places=2, default=100, help_text='رسوم تثبيت الإعلان في أعلى القائمة', max_digits=10, verbose_name='سعر تثبيت الإعلان'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='urgent_ad_price',
            field=models.DecimalField(decimal_places=2, default=30, help_text='رسوم إضافة علامة عاجل للإعلان', max_digits=10, verbose_name='سعر الإعلان العاجل'),
        ),
    ]
