# Generated by Django 5.2.7 on 2025-12-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_add_feature_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='require_verification_for_free_package',
            field=models.BooleanField(default=False, help_text='إذا كان مفعلاً، يتم منح الباقة المجانية فقط بعد التحقق من الإيميل ورقم الموبايل', verbose_name='التحقق مطلوب للباقة المجانية'),
        ),
    ]
