# Generated by Django 5.2.7 on 2025-12-30 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_add_verification_for_free_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='cart_service_fee_type',
            field=models.CharField(choices=[('fixed', 'رسوم ثابتة'), ('percentage', 'نسبة مئوية')], default='percentage', help_text='هل رسوم الخدمة ثابتة أم نسبة من سعر المنتج؟', max_length=20, verbose_name='نوع رسوم خدمة السلة'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='cart_service_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الثابت الذي يتم خصمه من الناشر عند البيع', max_digits=10, verbose_name='رسوم خدمة السلة الثابتة'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='cart_service_instructions',
            field=models.TextField(blank=True, default='عند تفعيل السلة، سيتم خصم رسوم خدمة من ثمن المنتج عند البيع. يجب أن يكون السعر شاملاً لهذه الرسوم ورسوم التوصيل.', help_text='التعليمات التي تظهر للناشر عند تفعيل السلة', verbose_name='تعليمات خدمة السلة للناشر'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='cart_service_percentage',
            field=models.DecimalField(decimal_places=2, default=5, help_text='النسبة المئوية من سعر المنتج التي يتم خصمها من الناشر', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة رسوم خدمة السلة'),
        ),
    ]
