# Generated by Django 5.2.7 on 2025-12-30 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_siteconfiguration_cart_service_fee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='deleted_ads_retention_days',
            field=models.PositiveIntegerField(default=90, help_text='عدد الأيام قبل الحذف النهائي للإعلانات المحذوفة من قاعدة البيانات. القيمة الافتراضية: 90 يوم (3 شهور)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(730)], verbose_name='مدة الاحتفاظ بالإعلانات المحذوفة (يوم)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='expired_ads_retention_days',
            field=models.PositiveIntegerField(default=365, help_text='عدد الأيام قبل الحذف النهائي للإعلانات المنتهية من قاعدة البيانات. القيمة الافتراضية: 365 يوم (سنة)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1825)], verbose_name='مدة الاحتفاظ بالإعلانات المنتهية (يوم)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_deleted_ads_to_publisher',
            field=models.BooleanField(default=True, help_text='السماح للناشر برؤية إعلاناته المحذوفة قبل الحذف النهائي', verbose_name='إظهار الإعلانات المحذوفة للناشر'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_expired_ads_to_publisher',
            field=models.BooleanField(default=True, help_text='السماح للناشر برؤية إعلاناته المنتهية', verbose_name='إظهار الإعلانات المنتهية للناشر'),
        ),
    ]
