# Generated by Django 5.2.7 on 2025-12-31 05:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_add_ads_retention_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='buyer_safety_notes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='\n        <ul>\n            <li>قابل البائع في مكان عام وآمن</li>\n            <li>تحقق من المنتج جيداً قبل الشراء</li>\n            <li>لا تحول أي أموال قبل استلام المنتج</li>\n            <li>احذر من العروض المشبوهة أو الأسعار المبالغ فيها</li>\n            <li>استخدم طرق الدفع الآمنة</li>\n        </ul>\n        ', help_text='النصائح الإرشادية التي تظهر للمشتري بجوار الإعلان', verbose_name='نصائح الأمان للمشترين'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='buyer_safety_notes_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='\n        <ul>\n            <li>قابل البائع في مكان عام وآمن</li>\n            <li>تحقق من المنتج جيداً قبل الشراء</li>\n            <li>لا تحول أي أموال قبل استلام المنتج</li>\n            <li>احذر من العروض المشبوهة أو الأسعار المبالغ فيها</li>\n            <li>استخدم طرق الدفع الآمنة</li>\n        </ul>\n        ', verbose_name='نصائح الأمان للمشترين بالعربية'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='buyer_safety_notes_enabled',
            field=models.BooleanField(default=True, help_text='إظهار/إخفاء نصائح الأمان في صفحة تفاصيل الإعلان', verbose_name='تفعيل نصائح الأمان للمشترين'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='buyer_safety_notes_title',
            field=models.CharField(default='نصائح للأمان', max_length=200, verbose_name='عنوان نصائح الأمان'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='buyer_safety_notes_title_ar',
            field=models.CharField(default='نصائح للأمان', max_length=200, verbose_name='عنوان نصائح الأمان بالعربية'),
        ),
    ]
