# Generated by Django 5.2.7 on 2025-12-31 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_siteconfiguration_buyer_safety_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, help_text='شعار الموقع الذي يظهر في الإعلانات بدون صور', null=True, upload_to='site/logos/', verbose_name='شعار الموقع - Site Logo'),
        ),
    ]
