# Generated by Django 5.2.7 on 2026-01-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_populate_payment_method_configs"),
        ("content", "0022_add_site_logo"),
    ]

    operations = []
