# Generated by Django 5.2.7 on 2026-01-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_populate_about_page_sections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentmethodconfig",
            name="cod_requires_deposit",
            field=models.BooleanField(
                default=True,
                help_text="إذا كان مفعلاً، يجب دفع مبلغ الحجز قبل تأكيد الطلب",
                verbose_name="يتطلب الدفع عند الاستلام مبلغ حجز",
            ),
        ),
    ]
