# Generated by Django 5.2.7 on 2026-01-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_alter_paymentmethodconfig_cod_requires_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='modal_button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_button_text_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_button_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_content_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='modal_title_ar',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='show_modal',
        ),
    ]
