# Generated by Django 5.2.7 on 2026-01-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_remove_homepage_modal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_why_choose_us',
            field=models.BooleanField(default=True, verbose_name='عرض قسم لماذا نحن - Show Why Choose Us'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_us_subtitle',
            field=models.TextField(blank=True, help_text='نص توضيحي قصير أسفل العنوان (اختياري)', verbose_name='عنوان فرعي - Subtitle'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_us_subtitle_ar',
            field=models.TextField(blank=True, verbose_name='عنوان فرعي بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_us_title',
            field=models.CharField(default='Why Choose Us?', max_length=200, verbose_name='عنوان قسم لماذا نحن - Why Choose Us Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='why_choose_us_title_ar',
            field=models.CharField(default='لماذا إدريسي مارت للمساحة؟', max_length=200, verbose_name='عنوان قسم لماذا نحن بالعربية'),
        ),
        migrations.CreateModel(
            name='WhyChooseUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الميزة (مثل: دقة عالية)', max_length=200, verbose_name='العنوان - Title')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربية')),
                ('description', models.TextField(help_text='وصف الميزة', verbose_name='الوصف - Description')),
                ('description_ar', models.TextField(verbose_name='الوصف بالعربية')),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='أيقونة FontAwesome (مثل: fas fa-check-circle, fas fa-star, fas fa-award)', max_length=50, verbose_name='الأيقونة - Icon')),
                ('order', models.IntegerField(default=0, help_text='ترتيب ظهور الميزة', verbose_name='الترتيب - Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط - Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us_features', to='content.homepage', verbose_name='الصفحة الرئيسية - Home Page')),
            ],
            options={
                'verbose_name': 'ميزة - لماذا نحن',
                'verbose_name_plural': 'مميزات - لماذا نحن',
                'ordering': ['order', 'id'],
            },
        ),
    ]
