# Generated by Django 5.2.7 on 2026-01-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_homepage_show_why_choose_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_statistics',
            field=models.BooleanField(default=True, verbose_name='عرض قسم الإحصائيات - Show Statistics'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_icon',
            field=models.CharField(default='fas fa-award', help_text='أيقونة FontAwesome (مثل: fas fa-award)', max_length=100, verbose_name='الإحصائية 1 - الأيقونة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 1 - العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 1 - العنوان الفرعي بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_title',
            field=models.CharField(default='سنة خبرة', max_length=200, verbose_name='الإحصائية 1 - العنوان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_title_ar',
            field=models.CharField(default='سنة خبرة', max_length=200, verbose_name='الإحصائية 1 - العنوان بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat1_value',
            field=models.IntegerField(default=15, help_text='القيمة العددية (مثل: 15)', verbose_name='الإحصائية 1 - القيمة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_icon',
            field=models.CharField(default='fas fa-users', help_text='أيقونة FontAwesome (مثل: fas fa-users)', max_length=100, verbose_name='الإحصائية 2 - الأيقونة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 2 - العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 2 - العنوان الفرعي بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_title',
            field=models.CharField(default='عميل راضٍ', max_length=200, verbose_name='الإحصائية 2 - العنوان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_title_ar',
            field=models.CharField(default='عميل راضٍ', max_length=200, verbose_name='الإحصائية 2 - العنوان بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat2_value',
            field=models.IntegerField(default=150, help_text='القيمة العددية (مثل: 150)', verbose_name='الإحصائية 2 - القيمة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_icon',
            field=models.CharField(default='fas fa-drafting-compass', help_text='أيقونة FontAwesome (مثل: fas fa-drafting-compass)', max_length=100, verbose_name='الإحصائية 3 - الأيقونة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 3 - العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 3 - العنوان الفرعي بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_title',
            field=models.CharField(default='خريطة مساحية', max_length=200, verbose_name='الإحصائية 3 - العنوان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_title_ar',
            field=models.CharField(default='خريطة مساحية', max_length=200, verbose_name='الإحصائية 3 - العنوان بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat3_value',
            field=models.IntegerField(default=500, help_text='القيمة العددية (مثل: 500)', verbose_name='الإحصائية 3 - القيمة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat4_icon',
            field=models.CharField(default='fas fa-map', help_text='أيقونة FontAwesome (مثل: fas fa-map)', max_length=100, verbose_name='الإحصائية 4 - الأيقونة'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat4_subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 4 - العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat4_subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='الإحصائية 4 - العنوان الفرعي بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat4_title',
            field=models.CharField(default='مشروع مساحي منجز', max_length=200, verbose_name='الإحصائية 4 - العنوان'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat4_title_ar',
            field=models.CharField(default='مشروع مساحي منجز', max_length=200, verbose_name='الإحصائية 4 - العنوان بالعربية'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='stat4_value',
            field=models.IntegerField(default=250, help_text='القيمة العددية (مثل: 250)', verbose_name='الإحصائية 4 - القيمة'),
        ),
    ]
