# Generated by Django 5.2.7 on 2026-01-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_homepage_show_statistics_homepage_stat1_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_dark",
            field=models.ImageField(
                blank=True,
                help_text="شعار الموقع الذي يظهر في الوضع الداكن (Dark Mode). إذا تُرك فارغاً، سيُستخدم الشعار الافتراضي",
                null=True,
                upload_to="site/logos/",
                verbose_name="شعار الموقع - الوضع الداكن",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_light",
            field=models.ImageField(
                blank=True,
                help_text="شعار الموقع الذي يظهر في الوضع الفاتح (Light Mode). إذا تُرك فارغاً، سيُستخدم الشعار الافتراضي",
                null=True,
                upload_to="site/logos/",
                verbose_name="شعار الموقع - الوضع الفاتح",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="logo_mini",
            field=models.ImageField(
                blank=True,
                help_text="شعار مصغر يظهر في صفحات التحميل (Loader). إذا تُرك فارغاً، سيُستخدم الشعار الافتراضي",
                null=True,
                upload_to="site/logos/",
                verbose_name="شعار مصغر - Loader",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat1_icon",
            field=models.CharField(
                default="fas fa-user-friends",
                help_text="أيقونة FontAwesome (مثل: fas fa-user-friends)",
                max_length=100,
                verbose_name="الإحصائية 1 - الأيقونة",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat1_subtitle",
            field=models.CharField(
                blank=True,
                default="Offices, Engineers & Companies",
                max_length=300,
                verbose_name="الإحصائية 1 - العنوان الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat1_subtitle_ar",
            field=models.CharField(
                blank=True,
                default="مكاتب، مهندسين، وشركات",
                max_length=300,
                verbose_name="الإحصائية 1 - العنوان الفرعي بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat1_title",
            field=models.CharField(
                default="Active Advertisers",
                max_length=200,
                verbose_name="الإحصائية 1 - العنوان",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat1_title_ar",
            field=models.CharField(
                default="معلنين نشطين",
                max_length=200,
                verbose_name="الإحصائية 1 - العنوان بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat2_icon",
            field=models.CharField(
                default="fas fa-bullhorn",
                help_text="أيقونة FontAwesome (مثل: fas fa-bullhorn)",
                max_length=100,
                verbose_name="الإحصائية 2 - الأيقونة",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat2_subtitle",
            field=models.CharField(
                blank=True,
                default="Services, Equipment & Job Opportunities",
                max_length=300,
                verbose_name="الإحصائية 2 - العنوان الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat2_subtitle_ar",
            field=models.CharField(
                blank=True,
                default="خدمات، معدات، وفرص عمل",
                max_length=300,
                verbose_name="الإحصائية 2 - العنوان الفرعي بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat2_title",
            field=models.CharField(
                default="Published Ads",
                max_length=200,
                verbose_name="الإحصائية 2 - العنوان",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat2_title_ar",
            field=models.CharField(
                default="إعلانات منشورة",
                max_length=200,
                verbose_name="الإحصائية 2 - العنوان بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat3_icon",
            field=models.CharField(
                default="fas fa-chart-line",
                help_text="أيقونة FontAwesome (مثل: fas fa-chart-line)",
                max_length=100,
                verbose_name="الإحصائية 3 - الأيقونة",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat3_subtitle",
            field=models.CharField(
                blank=True,
                default="Interested in Surveying Field",
                max_length=300,
                verbose_name="الإحصائية 3 - العنوان الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat3_subtitle_ar",
            field=models.CharField(
                blank=True,
                default="مهتمون بالمجال المساحي",
                max_length=300,
                verbose_name="الإحصائية 3 - العنوان الفرعي بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat3_title",
            field=models.CharField(
                default="Monthly Visits",
                max_length=200,
                verbose_name="الإحصائية 3 - العنوان",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat3_title_ar",
            field=models.CharField(
                default="زيارات شهرية",
                max_length=200,
                verbose_name="الإحصائية 3 - العنوان بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat4_icon",
            field=models.CharField(
                default="fas fa-th-large",
                help_text="أيقونة FontAwesome (مثل: fas fa-th-large)",
                max_length=100,
                verbose_name="الإحصائية 4 - الأيقونة",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat4_subtitle",
            field=models.CharField(
                blank=True,
                default="Surveying - Engineering - GIS",
                max_length=300,
                verbose_name="الإحصائية 4 - العنوان الفرعي",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat4_subtitle_ar",
            field=models.CharField(
                blank=True,
                default="مساحة – هندسة – GIS",
                max_length=300,
                verbose_name="الإحصائية 4 - العنوان الفرعي بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat4_title",
            field=models.CharField(
                default="Supported Specializations",
                max_length=200,
                verbose_name="الإحصائية 4 - العنوان",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="stat4_title_ar",
            field=models.CharField(
                default="تخصصات مدعومة",
                max_length=200,
                verbose_name="الإحصائية 4 - العنوان بالعربية",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="شعار الموقع الذي يظهر في الإعلانات بدون صور (الشعار الافتراضي)",
                null=True,
                upload_to="site/logos/",
                verbose_name="شعار الموقع - Site Logo",
            ),
        ),
    ]
