# Generated by Django 5.2.7 on 2026-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0030_add_theme_logos"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="add_video_price",
            field=models.DecimalField(
                decimal_places=2,
                default=25,
                help_text="رسوم إرفاق فيديو بالإعلان",
                max_digits=10,
                verbose_name="سعر إضافة فيديو",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="auto_refresh_price",
            field=models.DecimalField(
                decimal_places=2,
                default=35,
                help_text="رسوم تحديث تاريخ الإعلان تلقائياً كل يوم لمدة 7 أيام",
                max_digits=10,
                verbose_name="سعر التحديث التلقائي",
            ),
        ),
    ]
