# Generated by Django 5.2.7 on 2026-04-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0033_add_newsletter_model"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="newsletter",
            new_name="content_new_email_2fd3aa_idx",
            old_name="content_new_email_idx",
        ),
        migrations.RenameIndex(
            model_name="newsletter",
            new_name="content_new_is_acti_d0c575_idx",
            old_name="content_new_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="newsletter",
            new_name="content_new_created_0998ef_idx",
            old_name="content_new_created_at_idx",
        ),
    ]
