# Generated by Django 5.2.14 on 2026-05-27 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0034_add_paid_advertisement_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="نسبة الضريبة المضافة على المعاملات (0 = بدون ضريبة)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="نسبة الضريبة (%)",
            ),
        ),
    ]
