# Generated by Django 5.2.14 on 2026-05-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0035_add_tax_rate_to_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogcategory",
            name="description_en",
            field=models.TextField(blank=True, verbose_name="الوصف (إنجليزي)"),
        ),
        migrations.AlterField(
            model_name="blogcategory",
            name="description",
            field=models.TextField(blank=True, verbose_name="الوصف (عربي)"),
        ),
    ]
