# Generated by Django 5.2.14 on 2026-06-03 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0036_add_description_en_to_blogcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TubeCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="الاسم")),
                (
                    "name_en",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="الاسم بالإنجليزية"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="fas fa-play-circle",
                        max_length=60,
                        verbose_name="أيقونة FontAwesome",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#e63946", max_length=7, verbose_name="لون HEX"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("is_active", models.BooleanField(default=True, verbose_name="نشطة")),
            ],
            options={
                "verbose_name": "فئة إدريسي تيوب",
                "verbose_name_plural": "فئات إدريسي تيوب",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TubeVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="العنوان")),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="العنوان بالإنجليزية"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="الوصف بالإنجليزية"),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="رابط YouTube أو Vimeo أو رابط مباشر mp4",
                        verbose_name="رابط الفيديو",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tube/thumbnails/",
                        verbose_name="صورة مصغرة (اختياري)",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="المدة مثل 12:30"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="المشاهدات"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منشور"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="الترتيب")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="videos",
                        to="content.tubecategory",
                        verbose_name="الفئة",
                    ),
                ),
            ],
            options={
                "verbose_name": "فيديو إدريسي تيوب",
                "verbose_name_plural": "فيديوهات إدريسي تيوب",
                "ordering": ["-created_at"],
            },
        ),
    ]
